dojo.require("dojox.validate.web");dojo.require("dijit._editor.range");dojo.require("idealista.widget.dialogbox");dojo.requireLocalization("idealista.i18n","users");var i18n=dojo.i18n.getLocalization("idealista.i18n","users");
function _onLoad(){assignPasswordInfo();dojo.byId("alert-login")&&(dojo.byId("pwd").onkeypress=chekPwdLength,dojo.byId("frmLogin").onsubmit=checkLogin,dojo.query("#frmLogin input").forEach(quitarErrorCampo));dojo.byId("alert-requestPasswordChange")&&(dojo.byId("frmRequestPasswordChange").onsubmit=function(a){var b=/^[p|P][0-9]{1,9}/.test(dojo.trim(dojo.byId("email").value))?!0:!1;dojox.validate.isEmailAddress(dojo.trim(dojo.byId("email").value))||b||(dojo.addClass(dijit.range.getAncestor(dojo.byId("email"),
/FIELDSET/),"error"),limpiarTextosError(),nuevoTextoError(i18n["private.user.validation.email"]),dojo.style(dojo.query(".alert")[0],"display",""),dojo.stopEvent(a))},dojo.query("#frmRequestPasswordChange input").forEach(quitarErrorCampo));dojo.byId("change-password")&&(dojo.byId("frmChangePassword").onsubmit=function(a){var b=!1;dojo.byId("pwdNuevo").onkeypress=chekPwdLength;var e=dojo.byId("pwdNuevo").value;4>e.length&&(dojo.addClass(dijit.range.getAncestor(dojo.byId("pwdNuevo"),/FIELDSET/),"error"),
dojo.style(dojo.query(".alert")[0],"display",""),nuevoTextoError(i18n["private.user.validation.password"]),b=!0);"alphanumeric"!=e.getFormat()&&(dojo.addClass(dijit.range.getAncestor(dojo.byId("pwdNuevo"),/FIELDSET/),"error"),dojo.style(dojo.query(".alert")[0],"display",""),nuevoTextoError(i18n["private.user.validation.password.alphanumeric"]),b=!0);b&&dojo.stopEvent(a)},dojo.query("#frmChangePassword input").forEach(quitarErrorCampo));dojo.byId("frmRegistroEmail")&&(dojo.query("#frmRegistroEmail input").forEach(quitarErrorCampo),
dojo.connect(dojo.byId("frmRegistroEmail"),"submit",function(a){var b=!0;limpiarErroresFrmRegistroAlta();limpiarTextosError();var e=/^[p|P][0-9]{1,9}/.test(dojo.trim(dojo.byId("email").value))?!0:!1;modules.validation.validateFields($("#frmRegistroEmail"))||e||(b=!1,nuevoTextoError(i18n["private.user.validation.email"]));b||(dojo.style(dojo.query(".alert")[0],"display",""),dojo.stopEvent(a))}));if(dojo.byId("registro-alta")){dojo.byId("pwd").onkeypress=chekPwdLength;dojo.byId("pwd2").onkeypress=chekPwdLength;
dojo.byId("frmRegistroAlta")&&(dojo.byId("frmRegistroAlta").onsubmit=checkRegistroAlta,dojo.query("#frmRegistroAlta input").forEach(quitarErrorCampo),dojo.byId("boletinproxy")&&(dojo.byId("boletinproxy").onclick=function(a){dojo.byId("boletinproxy").checked?dojo.byId("boletin").value="T":dojo.byId("boletin").value="F"}));if(dojo.byId("frmRegistroAlias")){dojo.query("#frmRegistroAlias input").forEach(quitarErrorCampo);dojo.connect(dojo.byId("frmRegistroAlias"),"submit",function(a){nameInput=document.getElementById("alias");
nameInput.value=modules.utils.stripHTML(nameInput.value);var b=!0;limpiarErroresFrmRegistroAlta();limpiarTextosError();""==dojo.byId("alias").value&&(b=!1,dojo.addClass(dijit.range.getAncestor(dojo.byId("alias"),/FIELDSET/),"error"),nuevoTextoError(i18n["private.user.validation.username"]));b||(dojo.style(dojo.query(".alert")[0],"display",""),dojo.stopEvent(a))});var b=function(a){dojo.byId("isFrmRegistroAlias").disabled=""};dojo.connect(dojo.byId("alias"),"keypress",b);dojo.connect(dojo.byId("cookie"),
"change",b)}dojo.byId("frmRegistroPassword")&&(dojo.query("#frmRegistroPassword input").forEach(quitarErrorCampo),dojo.connect(dojo.byId("frmRegistroPassword"),"submit",function(a){var b=!0;limpiarErroresFrmRegistroAlta();limpiarTextosError();4>dojo.byId("pwd").value.length&&(b=!1,dojo.addClass(dijit.range.getAncestor(dojo.byId("pwd"),/FIELDSET/),"error"),nuevoTextoError(i18n["private.user.validation.password"]));"alphanumeric"!=dojo.byId("pwd").value.getFormat()&&(b=!1,dojo.addClass(dijit.range.getAncestor(dojo.byId("pwd"),
/FIELDSET/),"error"),nuevoTextoError(i18n["private.user.validation.password.alphanumeric"]));dojo.byId("pwd").value!=dojo.byId("pwd2").value&&(b=!1,dojo.addClass(dijit.range.getAncestor(dojo.byId("pwd2"),/FIELDSET/),"error"),nuevoTextoError(i18n["private.user.validation.password.length"]));b||(dojo.style(dojo.query(".alert")[0],"display",""),dojo.stopEvent(a))}),b=function(a){dojo.byId("isFrmRegistroPassword").disabled=""},dojo.connect(dojo.byId("pwd"),"keypress",b),dojo.connect(dojo.byId("pwd2"),
"keypress",b));dojo.byId("frmRegistroBoletines")&&(b=function(a){dojo.byId("isFrmNewsRegistry").disabled=""},dojo.connect(dojo.byId("weekly"),"click",b),dojo.connect(dojo.byId("daily"),"click",b),dojo.connect(dojo.byId("idealistaNews"),"click",b),dojo.connect(dojo.byId("favouriteNews"),"click",b))}dojo.byId("registro-login")&&(dojo.byId("pwd").onkeypress=chekPwdLength,dojo.byId("frmRegistroLogin").onsubmit=checkRegistroLogin,dojo.query("#frmRegistroLogin input").forEach(quitarErrorCampo));dojo.byId("registro-email")&&
(dojo.byId("pwd").onkeypress=chekPwdLength,dojo.byId("frmRegistroEmail").onsubmit=checkRegistroEmail,dojo.query("#frmRegistroEmail input").forEach(quitarErrorCampo));dojo.byId("select-email")&&(dojo.byId("mail").onclick=function(a){dojo.byId("otheremail").checked=!0},dojo.byId("frmSelectEmail").onsubmit=checkSelectEmail,dojo.query("#frmSelectEmail input").forEach(quitarErrorCampo));dojo.query("#main form input[class]")&&dojo.query("#main form input[class]")[0]&&0==dojo.query(".alerts-login").length&&
(dojo.query("#main form input[class]")[0].setAttribute("bypassOnFocus","true"),dojo.query("#main form input[class]")[0].focus(),dojo.query("#main form input[class]")[0].setAttribute("bypassOnFocus",""));if(0<dojo.query(".alerts-login").length){var a=dojo.query("#main form input[class]")[0].value;-1==a.indexOf("@")&&(dojo.connect(dojo.query("#main form input[class]")[0],"onfocus",function(){dojo.query("#main form input[class]")[0].value==a&&(dojo.query("#main form input[class]")[0].value="")}),dojo.connect(dojo.query("#main form input[class]")[0],
"onblur",function(){""==dojo.query("#main form input[class]")[0].value&&(dojo.query("#main form input[class]")[0].value=a)}));dojo.connect(dojo.byId("doLogin"),"onclick",function(a){a.preventDefault();dojo.byId("id_apuntadoF").checked&&""==dojo.query("#main form input[class]")[0].value?(dojo.addClass(dojo.query("#main form input[class]")[0],"error"),dojo.connect(dojo.query("#main form input[class]")[0],"onfocus",function(){dojo.removeClass(dojo.query("#main form input[class]")[0],"error")})):(a=dojo.byId("id_apuntadoT").checked?
"login":"alta",dojo.byId("frmRegistroEmail").action=dojo.attr(dojo.byId("frmRegistroEmail"),"data-url-"+a),dojo.byId("frmRegistroEmail").submit())});dojo.connect(dojo.byId("pwd"),"onfocus",function(){dojo.byId("id_apuntadoT").checked=!0})}else dojo.byId("id_apuntadoT")&&(dojo.connect(dojo.byId("id_apuntadoT"),"onclick",function(){dojo.style(dojo.query(".dont-have-text")[0],"display","none");dojo.style(dojo.byId("password-control"),"display","block");dojo.style(dojo.query(".form-fld-check")[0],"display",
"block")}),dojo.connect(dojo.byId("id_apuntadoF"),"onclick",function(){dojo.style(dojo.query(".dont-have-text")[0],"display","inline-block");dojo.style(dojo.byId("password-control"),"display","none");dojo.style(dojo.query(".form-fld-check")[0],"display","none");dojo.byId("pwd").value="";dojo.byId("cookie").checked=!1}));idealista.comun.manageXitiPrimaryConversions();dojo.byId("retarded-link")&&setTimeout(function(){dojo.style(dojo.byId("retarded-link"),"visibility","visible")},5E3);dojo.byId("goToFlow")&&
dojo.connect(dojo.byId("goToFlow"),"click",function(a){a.preventDefault();window.history.back()})}dojo.addOnLoad(_onLoad);assignPasswordInfo=function(){dojo.byId("aPassInfo")&&(idealista.widget.dialogbox.init(),dojo.connect(dojo.byId("aPassInfo"),"onclick",function(b){dijit.byId("idealista_widget_dialogbox_0").show();dojo.stopEvent(b)}))};function ponApuntado(){dojo.byId("fd_havepasswd")&&(dojo.byId("fd_havepasswd").checked=!0)}
function checkEnter(b){!b&&event&&(b=event);13==(b.keyCode||b.which)&&submitFrm()}function chekPwdLength(b){!b&&event&&(b=event);var a=b.keyCode||b.which;20==(b.srcElement||b.target).value.length&&8!=a&&alert(i18n["private.user.validation.password.maxlength"])}
function quitarErrorCampo(b){dojo.connect(b,"focus",function(a){a=a||event;a=a.target||a.srcElement;(!a.getAttribute("bypassOnFocus")||a.getAttribute("bypassOnFocus")&&"true"!=a.getAttribute("bypassOnFocus"))&&dijit.range.getAncestor(a,/FIELDSET/)&&dojo.removeClass(dijit.range.getAncestor(a,/FIELDSET/),"error")})}function nuevoTextoError(b){var a={},a=document.createElement("P");a.innerHTML=b;dojo.place(a,dojo.query(".alert")[0],"last")}
function limpiarTextosError(){dojo.query(".alert p").forEach(function(b){dojo.query(".alert")[0].removeChild(b)})}
function checkRegistroAlta(b){var a=!0;limpiarErroresFrmRegistroAlta();limpiarTextosError();dojox.validate.isEmailAddress(dojo.trim(dojo.byId("email").value))||(a=!1,dojo.addClass(dijit.range.getAncestor(dojo.byId("email"),/FIELDSET/),"error"),nuevoTextoError(i18n["private.user.validation.email"]));""==dojo.byId("alias").value&&(a=!1,dojo.addClass(dijit.range.getAncestor(dojo.byId("alias"),/FIELDSET/),"error"),nuevoTextoError(i18n["private.user.validation.username"]));if(dojo.byId("nick")){var c=
/[^0-9a-zA-Z\.\ _\-]+/gi,d=dojo.byId("nick").value;""===d?(a=!1,dojo.addClass(dijit.range.getAncestor(dojo.byId("nick"),/FIELDSET/),"error"),nuevoTextoError(i18n["alta.js.nick.vacio"])):" "===d.substring(0,1)||" "===d.substring(d.length-1,d.length)?(a=!1,dojo.addClass(dijit.range.getAncestor(dojo.byId("nick"),/FIELDSET/),"error"),nuevoTextoError(i18n["alta.js.nick.error_espacios"])):0<=d.indexOf("  ")?(a=!1,dojo.addClass(dijit.range.getAncestor(dojo.byId("nick"),/FIELDSET/),"error"),nuevoTextoError(i18n["alta.js.nick.error_variosespacios"])):
d.match(c)&&(a=!1,dojo.addClass(dijit.range.getAncestor(dojo.byId("nick"),/FIELDSET/),"error"),nuevoTextoError(i18n["update.nick.restriccion"]))}""==dojo.byId("pwd").value&&dojo.byId("boletinproxy")||(4>dojo.byId("pwd").value.length&&(a=!1,dojo.addClass(dijit.range.getAncestor(dojo.byId("pwd"),/FIELDSET/),"error"),nuevoTextoError(i18n["private.user.validation.password"])),"alphanumeric"!=dojo.byId("pwd").value.getFormat()&&(a=!1,dojo.addClass(dijit.range.getAncestor(dojo.byId("pwd"),/FIELDSET/),"error"),
nuevoTextoError(i18n["private.user.validation.password.alphanumeric"])),dojo.byId("pwd").value!=dojo.byId("pwd2").value&&(a=!1,dojo.addClass(dijit.range.getAncestor(dojo.byId("pwd2"),/FIELDSET/),"error"),nuevoTextoError(i18n["private.user.validation.password.length"])));dojo.byId("iAgreement").checked||(a=!1,dojo.addClass(dijit.range.getAncestor(dojo.byId("iAgreement"),/FIELDSET/),"error"),nuevoTextoError(i18n["private.user.validation.privacy.policy"]));dojo.byId("boletinproxy")&&!dojo.byId("boletinproxy").checked&&
(dojo.byId("accion").value="baja_boletin");a||(dojo.style(dojo.query(".alert")[0],"display",""),dojo.stopEvent(b))}
function limpiarErroresFrmRegistroAlta(){dojo.byId("email")&&dojo.removeClass(dijit.range.getAncestor(dojo.byId("email"),/FIELDSET/),"error");dojo.byId("alias")&&dojo.removeClass(dijit.range.getAncestor(dojo.byId("alias"),/FIELDSET/),"error");dojo.byId("nick")&&dojo.removeClass(dijit.range.getAncestor(dojo.byId("nick"),/FIELDSET/),"error");dojo.byId("pwd")&&dojo.removeClass(dijit.range.getAncestor(dojo.byId("pwd"),/FIELDSET/),"error");dojo.byId("pwd2")&&dojo.removeClass(dijit.range.getAncestor(dojo.byId("pwd2"),
/FIELDSET/),"error")}function checkRegistroLogin(b){var a=!0;limpiarErroresFrmRegistroLogin();limpiarTextosError();4>dojo.byId("pwd").value.length&&(a=!1,dojo.addClass(dijit.range.getAncestor(dojo.byId("pwd"),/FIELDSET/),"error"),nuevoTextoError(i18n["private.user.validation.password"]));a||(dojo.style(dojo.query(".alert")[0],"display",""),dojo.stopEvent(b))}function limpiarErroresFrmRegistroLogin(){dojo.removeClass(dijit.range.getAncestor(dojo.byId("pwd"),/FIELDSET/),"error")}
function checkRegistroEmail(b){var a=!0;dojo.eval("hActions \x3d "+dojo.byId("frmRegistroEmail").getAttribute("djActionConfig"));limpiarErroresFrmRegistroEmail();limpiarTextosError();var c=/^[p|P][0-9]{1,9}/.test(dojo.trim(dojo.byId("email").value))?!0:!1;dojox.validate.isEmailAddress(dojo.trim(dojo.byId("email").value))||c?dojo.byId("primeremail").value=dojo.byId("email").value:(a=!1,dojo.addClass(dijit.range.getAncestor(dojo.byId("email"),/FIELDSET/),"error"),nuevoTextoError(i18n["private.user.validation.email"]));
dojo.byId("id_apuntadoF").checked?dojo.byId("frmRegistroEmail").setAttribute("action",hActions.alta):dojo.byId("id_apuntadoT").checked&&(dojo.byId("frmRegistroEmail").setAttribute("action",hActions.login),4>dojo.byId("pwd").value.length&&(a=!1,dojo.addClass(dijit.range.getAncestor(dojo.byId("pwd"),/FIELDSET/),"error"),nuevoTextoError(i18n["private.user.validation.password"])));a||(dojo.style(dojo.query(".alert")[0],"display",""),dojo.stopEvent(b))}
function limpiarErroresFrmRegistroEmail(){dojo.removeClass(dijit.range.getAncestor(dojo.byId("pwd"),/FIELDSET/),"error");dojo.removeClass(dijit.range.getAncestor(dojo.byId("email"),/FIELDSET/),"error")}
function checkRecibirPwd(b){var a=!0;dojo.style(dojo.query(".alert")[0],"display","none");dojo.removeClass(dijit.range.getAncestor(dojo.byId("mail"),/FIELDSET/),"error");var c=/^[p|P][0-9]{1,9}/.test(dojo.trim(dojo.byId("mail").value))?!0:!1;dojox.validate.isEmailAddress(dojo.trim(dojo.byId("mail").value))||c||(a=!1,dojo.addClass(dijit.range.getAncestor(dojo.byId("mail"),/FIELDSET/),"error"),dojo.query(".alert p")[0].innerHTML=i18n["private.user.validation.email"],dojo.style(dojo.query(".alert")[0],
"display",""));a||dojo.stopEvent(b)}
function checkLogin(b){var a=!0;limpiarErroresFrmLogin();limpiarTextosError();var c=/^[p|P][0-9]{1,9}/.test(dojo.trim(dojo.byId("email").value))?!0:!1;dojox.validate.isEmailAddress(dojo.trim(dojo.byId("email").value))||c||(a=!1,dojo.addClass(dijit.range.getAncestor(dojo.byId("email"),/FIELDSET/),"error"),nuevoTextoError(i18n["private.user.validation.email"]));4>dojo.byId("pwd").value.length&&(a=!1,dojo.addClass(dijit.range.getAncestor(dojo.byId("pwd"),/FIELDSET/),"error"),nuevoTextoError(i18n["private.user.validation.password"]));
a||(dojo.style(dojo.query(".alert")[0],"display",""),dojo.stopEvent(b))}function limpiarErroresFrmLogin(){dojo.removeClass(dijit.range.getAncestor(dojo.byId("pwd"),/FIELDSET/),"error");dojo.removeClass(dijit.range.getAncestor(dojo.byId("email"),/FIELDSET/),"error")}
function checkSelectEmail(b){var a=!0;limpiarErroresFrmSelectEmail();limpiarTextosError();if(!0==dojo.byId("firstemail").checked)dojo.byId("primeremail").value=dojo.byId("firstemail").value;else if(!0==dojo.byId("secondemail").checked)dojo.byId("primeremail").value=dojo.byId("secondemail").value;else if(!0==dojo.byId("otheremail").checked){dojo.byId("primeremail").value=dojo.byId("mail").value;var c=/^[p|P][0-9]{1,9}/.test(dojo.trim(dojo.byId("email").value))?!0:!1;dojox.validate.isEmailAddress(dojo.trim(dojo.byId("mail").value))||
c||(a=!1,dojo.addClass(dijit.range.getAncestor(dojo.byId("mail"),/FIELDSET/),"error"),nuevoTextoError(i18n["private.user.validation.email"]))}a||(dojo.style(dojo.query(".alert")[0],"display",""),dojo.stopEvent(b))}function limpiarErroresFrmSelectEmail(){dojo.removeClass(dijit.range.getAncestor(dojo.byId("mail"),/FIELDSET/),"error")}
function showConfirmationPopup(b,a){b.preventDefault();var c=i18n["private.user.update.cardreferences.delete.question"],d='\x3cinput type\x3d"button" class\x3d"btn regular aceptar" value\x3d"'+i18n["private.user.update.cardreferences.delete.accept"]+'" /\x3e',e='\x3ca href\x3d"#" class\x3d"cancel"\x3e'+i18n["private.user.update.cardreferences.delete.cancel"]+"\x3c/a\x3e";dojo.byId("pgwCardReferenceId").value=a;dialog=new modules.modal({title:c,buttons:d+e});dialog.show();dojo.query("#"+dialog.options.id+
" .cancel").forEach(function(a){dojo.connect(a,"onclick",function(a){a.preventDefault();dialog.destroy()})});dojo.query("#"+dialog.options.id+" .aceptar").forEach(function(a){dojo.connect(a,"onclick",function(a){a.preventDefault();dojo.byId("formPGWCardReferences").submit()})})};