(function(g){var window=this;var Fpa=function(a,b){return g.Wb(a,b)},M4=function(a,b,c){a.l.set(b,c)},N4=function(a){M4(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.A)()).toString(36));
return a},O4=function(a,b,c){g.La(c)||(c=[String(c)]);
g.Um(a.l,b,c)},Gpa=function(a,b){var c=[];
g.Xi(b,function(d){try{var e=g.En.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ca(e)?g.Dn(e)&&c.push(d):c.push(d)},a);
return c},Hpa=function(a,b){var c=Gpa(a,b);
(0,g.z)(c,function(d){g.En.prototype.remove.call(this,d)},a)},P4=function(a){if(a.Zc){if(a.Zc.locationOverrideToken)return{locationOverrideToken:a.Zc.locationOverrideToken};
if(null!=a.Zc.latitudeE7&&null!=a.Zc.longitudeE7)return{latitudeE7:a.Zc.latitudeE7,longitudeE7:a.Zc.longitudeE7}}return null},Ipa=function(a,b){g.ab(a,b)||a.push(b)},Q4=function(a){var b=0,c;
for(c in a)b++;return b},R4=function(a,b){var c=b instanceof g.xc?b:g.Cc(b,/^data:image\//i.test(b));
a.src=g.yc(c)},S4=function(){},Jpa=function(a){try{return g.u.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Kpa=function(a){if(a.wd&&"function"==typeof a.wd)return a.wd();
if(g.Da(a))return a.split("");if(g.Ma(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Sb(a)},Lpa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ma(a)||g.Da(a))(0,g.z)(a,b,void 0);else{if(a.Wd&&"function"==typeof a.Wd)var c=a.Wd();else if(a.wd&&"function"==typeof a.wd)c=void 0;else if(g.Ma(a)||g.Da(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Tb(a);d=Kpa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},Mpa=function(a,b,c,d){var e=new g.Im(null,void 0);
a&&g.Jm(e,a);b&&g.Km(e,b);c&&g.Lm(e,c);d&&(e.i=d);return e},T4=function(a,b){g.Go[a]=!0;
var c=g.Eo();c&&c.publish.apply(c,arguments);g.Go[a]=!1},U4=function(a){try{var b=(0,g.Tx)(),c=(0,g.Sx)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},Npa=function(){var a=(0,g.Sx)();
a&&Hpa(a,a.g.af(!0))},V4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Fm;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Opa(this,a.capabilities||""),Ppa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},Opa=function(a,b){a.capabilities.clear();
(0,g.Vd)(b.split(","),g.Ra(Fpa,Qpa)).forEach(function(c){a.capabilities.add(c)})},Ppa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},W4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},X4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},Y4=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Rpa=function(a){return new W4(a)},Z4=function(a){return g.La(a)?(0,g.ee)(a,Rpa):[]},$4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},a5=function(a){return g.La(a)?"["+(0,g.ee)(a,$4).join(",")+"]":"null"},b5=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Spa=function(a){return(0,g.ee)(a,function(b){return{key:b.id,
name:b.name}})},c5=function(a,b){return g.Ya(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},d5=function(a,b){return g.Ya(a,function(c){return X4(c,b)})},e5=function(){var a=g.Vx("yt-remote-connected-devices")||[];
g.rb(a);return a},Tpa=function(a){if(g.bb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.ee)(a,function(d,e){return 0==e?d:d.substring(c.length)})},f5=function(a){g.Ux("yt-remote-connected-devices",a,86400)},h5=function(){if(g5)return g5;
var a=g.Vx("yt-remote-device-id");a||(a=b5(),g.Ux("yt-remote-device-id",a,31536E3));for(var b=e5(),c=1,d=a;g.ab(b,d);)c++,d=a+"#"+c;return g5=d},i5=function(){var a=e5(),b=h5();
g.ab(a,b);g.ZK()&&g.tb(a,b);a=Tpa(a);if(g.bb(a))try{g.tr("remote_sid")}catch(c){}else try{g.sr("remote_sid",a.join(","),-1)}catch(c){}},j5=function(){return g.Vx("yt-remote-session-browser-channel")},k5=function(){return g.Vx("yt-remote-local-screens")||[]},l5=function(){g.Ux("yt-remote-lounge-token-expiration",!0,86400)},Upa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.ee)(k5(),function(d){return d.loungeToken}),c=(0,g.ee)(a,function(d){return d.loungeToken});
(0,g.Xg)(c,function(d){return!g.ab(b,d)})&&l5();
g.Ux("yt-remote-local-screens",a,31536E3)},Vpa=function(a,b){g.Ux("yt-remote-session-browser-channel",a);
g.Ux("yt-remote-session-screen-id",b);var c=e5(),d=h5();g.ab(c,d)||c.push(d);f5(c);i5()},m5=function(a){a||(U4("yt-remote-session-screen-id"),U4("yt-remote-session-video-id"));
i5();a=e5();g.eb(a,h5());f5(a)},o5=function(){if(!n5){var a=g.On();
a&&(n5=new g.yn(a))}return n5?!!n5.get("yt-remote-use-staging-server"):!1},p5=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},q5=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},s5=function(a){a.length?r5(a.shift(),function(){s5(a)}):t5()},Wpa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},r5=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},t5=function(){var a=q5();
a&&a(!1,"No cast extension found")},u5=function(){if(Xpa){var a=2,b=q5(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;r5("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",t5,c)}},Ypa=function(){u5();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);s5(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},v5=function(a,b,c){g.F.call(this);
this.w=null!=c?(0,g.x)(a,c):a;this.Sc=b;this.u=(0,g.x)(this.VB,this);this.g=!1;this.i=0;this.l=this.za=null;this.o=[]},w5=function(a){if(g.u.JSON)try{return g.u.JSON.parse(a)}catch(b){}return Jpa(a)},x5=function(){},y5=function(){},z5=function(){},B5=function(a){return(a=A5(a))?new ActiveXObject(a):new XMLHttpRequest},A5=function(a){if(!a.i&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.i=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.i},C5=function(a,b,c,d){this.g=a;
this.l=b;this.B=c;this.w=d||1;this.o=45E3;this.ba=new g.$Y(this);this.i=new g.el;this.i.setInterval(250)},E5=function(a,b,c){a.Jh=1;
a.Kf=N4(b.clone());a.eh=c;a.u=!0;D5(a,null)},F5=function(a,b,c,d,e){a.Jh=1;
a.Kf=N4(b.clone());a.eh=null;a.u=c;e&&(a.Qy=!1);D5(a,d)},D5=function(a,b){a.oi=(0,g.A)();
G5(a);a.rg=a.Kf.clone();O4(a.rg,"t",a.w);a.Dk=0;a.pc=a.g.Ho(a.g.pk()?b:null);0<a.kp&&(a.gn=new g.hl((0,g.x)(a.Pz,a,a.pc),a.kp));a.ba.ea(a.pc,"readystatechange",a.QK);var c=a.Mg?g.bc(a.Mg):{};a.eh?(a.Mn="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.pc.send(a.rg,a.Mn,a.eh,c)):(a.Mn="GET",a.Qy&&!g.Ld&&(c.Connection="close"),a.pc.send(a.rg,a.Mn,null,c));a.g.me(1)},N5=function(a,b,c){for(var d=!0;!a.Bg&&a.Dk<c.length;){var e=Zpa(a,c);
if(e==H5){4==b&&(a.cg=4,I5(15),d=!1);break}else if(e==J5){a.cg=4;I5(16);d=!1;break}else K5(a,e)}4==b&&0==c.length&&(a.cg=1,I5(17),d=!1);a.ne=a.ne&&d;d||(L5(a),M5(a))},Zpa=function(a,b){var c=a.Dk,d=b.indexOf("\n",c);
if(-1==d)return H5;c=Number(b.substring(c,d));if(isNaN(c))return J5;d+=1;if(d+c>b.length)return H5;var e=b.substr(d,c);a.Dk=d+c;return e},Q5=function(a,b){a.oi=(0,g.A)();
G5(a);var c=b?window.location.hostname:"";a.rg=a.Kf.clone();M4(a.rg,"DOMAIN",c);M4(a.rg,"t",a.w);try{a.re=new ActiveXObject("htmlfile")}catch(n){L5(a);a.cg=7;I5(22);M5(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in O5)k=O5[l];else if(l in P5)k=O5[l]=P5[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
O5[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Qc(g.qc("b/12014412"),d+"</body></html>");a.re.open();a.re.write(g.Lc(c));a.re.close();a.re.parentWindow.m=(0,g.x)(a.fK,a);a.re.parentWindow.d=(0,g.x)(a.Xx,a,!0);a.re.parentWindow.rpcClose=(0,g.x)(a.Xx,a,!1);c=a.re.createElement("DIV");a.re.parentWindow.document.body.appendChild(c);d=g.Bc(a.rg.toString());d=g.Zc(g.zc(d));d=g.Qc(g.qc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Rc(c,d);a.g.me(1)},G5=function(a){a.Tr=(0,g.A)()+a.o;
R5(a,a.o)},R5=function(a,b){if(null!=a.Fi)throw Error("WatchDog timer not null");
a.Fi=S5((0,g.x)(a.oK,a),b)},T5=function(a){a.Fi&&(g.u.clearTimeout(a.Fi),a.Fi=null)},M5=function(a){a.g.Ru()||a.Bg||a.g.Xm(a)},L5=function(a){T5(a);
g.Ai(a.gn);a.gn=null;a.i.stop();g.bZ(a.ba);if(a.pc){var b=a.pc;a.pc=null;b.abort();b.dispose()}a.re&&(a.re=null)},K5=function(a,b){try{a.g.Rx(a,b),a.g.me(4)}catch(c){}},V5=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;U5(a,b,function(k){k?c(!0):g.u.setTimeout(function(){V5(a,b,c,d,f)},f)})}},U5=function(a,b,c){var d=new Image;
d.onload=function(){try{W5(d),c(!0)}catch(e){}};
d.onerror=function(){try{W5(d),c(!1)}catch(e){}};
d.onabort=function(){try{W5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{W5(d),c(!1)}catch(e){}};
g.u.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
R4(d,a)},W5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},X5=function(a){this.g=a;
this.i=new x5},Z5=function(a){var b=Y5(a.g,a.Pi,"/mail/images/cleardot.gif");
N4(b);V5(b.toString(),5E3,(0,g.x)(a.aB,a),3,2E3);a.me(1)},a6=function(a){var b=a.g.D;
if(null!=b)I5(5),b?(I5(11),$5(a.g,a,!1)):(I5(12),$5(a.g,a,!0));else if(a.Ad=new C5(a,void 0,void 0,void 0),a.Ad.Mg=a.ip,b=a.g,b=Y5(b,b.pk()?a.oj:null,a.jp),I5(5),!g.Jd||g.od(10))O4(b,"TYPE","xmlhttp"),F5(a.Ad,b,!1,a.oj,!1);else{O4(b,"TYPE","html");var c=a.Ad;a=!!a.oj;c.Jh=3;c.Kf=N4(b.clone());Q5(c,a)}},b6=function(a){g.uk.call(this);
this.headers=new g.Fm;this.M=a||null;this.l=!1;this.R=this.g=null;this.W=this.D="";this.w=0;this.o="";this.u=this.aa=this.C=this.P=!1;this.B=0;this.G=null;this.X="";this.I=this.S=!1},$pa=function(a){return g.Jd&&g.ld(9)&&g.Fa(a.timeout)&&g.Ca(a.ontimeout)},aqa=function(a){return"content-type"==a.toLowerCase()},e6=function(a,b){a.l=!1;
a.g&&(a.u=!0,a.g.abort(),a.u=!1);a.o=b;a.w=5;c6(a);d6(a)},c6=function(a){a.P||(a.P=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},h6=function(a){if(a.l&&"undefined"!=typeof g.fZ)if(a.R[1]&&4==f6(a)&&2==a.getStatus())g6(a,"Local request error detected and ignored");
else if(a.C&&4==f6(a))g.fl(a.Tu,0,a);else if(a.dispatchEvent("readystatechange"),4==f6(a)){g6(a,"Request complete");a.l=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.tf(1,String(a.D));if(!f&&g.u.self&&g.u.self.location){var k=g.u.self.location.protocol;f=k.substr(0,k.length-1)}e=!bqa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.w=6;try{var l=2<f6(a)?a.g.statusText:""}catch(m){l=""}a.o=l+" ["+a.getStatus()+"]";c6(a)}}finally{d6(a)}}},d6=function(a,b){if(a.g){i6(a);
var c=a.g,d=a.R[0]?g.Ia:null;a.g=null;a.R=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},i6=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.G&&(g.u.clearTimeout(a.G),a.G=null)},f6=function(a){return a.g?a.g.readyState:0},j6=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},g6=function(a,b){return b+" ["+a.W+" "+a.D+" "+a.getStatus()+"]"},k6=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new x5;this.C=a||null;this.D=null!=b?b:null;this.w=c||!1},cqa=function(a,b){this.g=a;
this.map=b;this.context=null},l6=function(a){g.Xj.call(this,"statevent",a)},m6=function(a,b){g.Xj.call(this,"timingevent",a);
this.size=b},n6=function(a){g.Xj.call(this,"serverreachability",a)},r6=function(a){o6(a);
if(3==a.g){var b=a.Uj++,c=a.Fl.clone();M4(c,"SID",a.l);M4(c,"RID",b);M4(c,"TYPE","terminate");p6(a,c);b=new C5(a,a.l,b,void 0);b.Jh=2;b.Kf=N4(c.clone());R4(new Image,b.Kf.toString());b.oi=(0,g.A)();G5(b)}q6(a)},t6=function(a){a.uB(1,0);
a.Fl=Y5(a,null,a.hp);s6(a)},o6=function(a){a.Qf&&(a.Qf.abort(),a.Qf=null);
a.Nb&&(a.Nb.cancel(),a.Nb=null);a.bf&&(g.u.clearTimeout(a.bf),a.bf=null);u6(a);a.td&&(a.td.cancel(),a.td=null);a.Xf&&(g.u.clearTimeout(a.Xf),a.Xf=null)},v6=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new cqa(a.uG++,b));2!=a.g&&3!=a.g||s6(a)},s6=function(a){a.td||a.Xf||(a.Xf=S5((0,g.x)(a.Wx,a),0),a.Ch=0)},y6=function(a,b){if(1==a.g){if(!b){a.Uj=Math.floor(1E5*Math.random());
var c=a.Uj++,d=new C5(a,"",c,void 0);d.Mg=null;var e=w6(a),f=a.Fl.clone();M4(f,"RID",c);M4(f,"CVER","1");p6(a,f);E5(d,f,e);a.td=d;a.g=2}}else 3==a.g&&(b?x6(a,b):0==a.i.length||a.td||x6(a))},x6=function(a,b){if(b)if(6<a.Cg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.Uj-1;var d=w6(a)}else c=b.B,d=b.eh;else c=a.Uj++,d=w6(a);var e=a.Fl.clone();M4(e,"SID",a.l);M4(e,"RID",c);M4(e,"AID",a.Vh);p6(a,e);c=new C5(a,a.l,c,a.Ch+1);c.Mg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.td=c;E5(c,e,d)},p6=function(a,b){if(a.Pc){var c=a.Pc.uu();
c&&g.Mb(c,function(d,e){M4(b,e,d)})}},w6=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Cg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Cg?e:f-d;try{g.Mb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},z6=function(a){a.Nb||a.bf||(a.B=1,a.bf=S5((0,g.x)(a.Vx,a),0),a.wh=0)},B6=function(a){if(a.Nb||a.bf||3<=a.wh)return!1;
a.B++;a.bf=S5((0,g.x)(a.Vx,a),A6(a,a.wh));a.wh++;return!0},$5=function(a,b,c){a.Kn=c;
a.we=b.qf;a.w||t6(a)},u6=function(a){null!=a.Fg&&(g.u.clearTimeout(a.Fg),a.Fg=null)},A6=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},D6=function(a,b){if(2==b||9==b){var c=null;
a.Pc&&(c=null);var d=(0,g.x)(a.wL,a);c||(c=new g.Im("//www.google.com/images/cleardot.gif"),N4(c));U5(c.toString(),1E4,d)}else I5(2);C6(a,b)},C6=function(a,b){a.g=0;
a.Pc&&a.Pc.Gt(b);q6(a);o6(a)},q6=function(a){a.g=0;
a.we=-1;if(a.Pc)if(0==a.o.length&&0==a.i.length)a.Pc.Ao();else{g.ib(a.o);var b=g.ib(a.i);a.o.length=0;a.i.length=0;a.Pc.Ao(b)}},Y5=function(a,b,c){var d=g.Qm(c);
if(""!=d.g)b&&g.Km(d,b+"."+d.g),g.Lm(d,d.u);else{var e=window.location;d=Mpa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.bj&&g.Mb(a.bj,function(f,k){M4(d,k,f)});
M4(d,"VER",a.Cg);p6(a,d);return d},S5=function(a,b){if(!g.Na(a))throw Error("Fn must not be null and must be a function");
return g.u.setTimeout(function(){a()},b)},I5=function(a){E6.dispatchEvent(new l6(E6,a))},F6=function(){},G6=function(){this.g=[];
this.i=[]},dqa=function(a,b){this.action=a;
this.params=b||{}},H6=function(a,b){g.F.call(this);
this.g=new g.I(this.WJ,0,this);g.H(this,this.g);this.Sc=5E3;this.i=0;if(g.Na(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Na(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},I6=function(a,b,c){this.G=a;
this.w=b;this.l=new g.xn;this.i=new H6(this.aL,this);this.g=null;this.bb=!1;this.u=null;this.D="";this.C=this.o=0;this.B=[];this.I=c||!1},eqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Kn,sessionId:a.g.l,arrayId:a.g.Vh}},J6=function(a,b){a.C=b||0;
a.i.stop();a.g&&(3==a.g.g&&y6(a.g),r6(a.g));a.C=0},K6=function(a){return!!a.g&&3==a.g.g},fqa=function(a,b){(a.w.loungeIdToken=b)||a.i.stop()},L6=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=Number(g.tf(4,a))||"";b&&(this.port=":"+b);this.domain=g.uf(a)||"";a=g.Kb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Jb(a,"10.0")&&(this.i=!1))},M6=function(a,b){var c=a.g;
if(g.Ca(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.Df(c+b,{})},N6=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ra(a.o,d,!0),onError:g.Ra(a.l,e),Nd:g.Ra(a.u,e)};c&&(a.rb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.zp(b,a)},gqa=function(){var a=O6;
P6();Q6.push(a);R6(Q6)},S6=function(a,b){P6();
var c=Q6,d=hqa(a,String(b));g.bb(c)?iqa(d):(R6(c),(0,g.z)(c,function(e){e(d)}))},P6=function(){Q6||(Q6=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",Q6,void 0))},iqa=function(a){var b=(T6+1)%50;
T6=b;U6[b]=a;V6||(V6=49==b)},R6=function(a){var b=U6;
if(b[0]){var c=T6,d=V6?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.z)(a,function(f){f(e)})}while(d!=c);
U6=Array(50);T6=-1;V6=!1}},hqa=function(a,b){var c=((0,g.A)()-jqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},W6=function(a){g.O.call(this);
this.B=a;this.g=[]},X6=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},kqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Vd)(a.g,function(f){return!!c5(b,f)});
for(var d=0,e=b.length;d<e;d++)c=X6(a,b[d])||c;return c},lqa=function(a,b){var c=a.g.length;
a.g=(0,g.Vd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},Y6=function(a,b,c,d){g.O.call(this);
this.w=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.za=NaN},$6=function(a){W6.call(this,"LocalScreenService");
this.l=a;this.i=NaN;Z6(this);this.info("Initializing with "+a5(this.g))},a7=function(a){if(a.g.length){var b=(0,g.ee)(a.g,function(d){return d.id}),c=M6(a.l,"/pairing/get_lounge_token_batch");
N6(a.l,c,{screen_ids:b.join(",")},(0,g.x)(a.gC,a),(0,g.x)(a.fC,a))}},Z6=function(a){var b=Z4(k5());
b=(0,g.Vd)(b,function(c){return!c.uuid});
return kqa(a,b)},b7=function(a,b){Upa((0,g.ee)(a.g,Y4));
b&&l5()},d7=function(a,b){g.O.call(this);
this.w=b;var c=g.Vx("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.w(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.ab(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;c7("Initialized with "+g.Bj(this.g))},e7=function(a,b,c){var d=M6(a.u,"/pairing/get_screen_availability");
N6(a.u,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},f7=function(a,b){a:if(Q4(b)!=Q4(a.g))var c=!1;
else{c=g.Tb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(c7("Updated online screens: "+g.Bj(a.g)),a.g=b,a.N("screenChange"));mqa(a)},g7=function(a){isNaN(a.l)||g.Do(a.l);
a.l=g.Bo((0,g.x)(a.gr,a),0<a.o&&a.o<(0,g.A)()?2E4:1E4)},c7=function(a){S6("OnlineScreenService",a)},h7=function(a){var b={};
(0,g.z)(a.w(),function(c){c.token?b[c.token]=c.id:this.Gb("Requesting availability of screen w/o lounge token.")});
return b},mqa=function(a){a=g.Tb(g.Nb(a.g,function(b){return b}));
g.rb(a);a.length?g.Ux("yt-remote-online-screen-ids",a.join(","),60):U4("yt-remote-online-screen-ids")},i7=function(a){W6.call(this,"ScreenService");
this.w=a;this.i=this.l=null;this.o=[];this.u={};nqa(this)},k7=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Kd();if(k=(c?d5(k,c):null)||d5(k,b)){k.uuid=b;var l=j7(a,k);e7(a.i,l,function(m){e(m?l:null)})}else c?oqa(a,c,(0,g.x)(function(m){var n=j7(this,new W4({name:d,
screenId:c,loungeToken:m,dialId:b||""}));e7(this.i,n,function(q){e(q?n:null)})},a),f):e(null)},l7=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},oqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={rb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.zp(M6(a.w,"/pairing/get_lounge_token_batch"),e)},m7=function(a){a.g=a.l.Kd();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+a5(a.g))},nqa=function(a){n7(a);
a.l=new $6(a.w);a.l.subscribe("screenChange",(0,g.x)(a.nC,a));m7(a);a.o=Z4(g.Vx("yt-remote-automatic-screen-cache")||[]);n7(a);a.info("Initializing automatic screens: "+a5(a.o));a.i=new d7(a.w,(0,g.x)(a.Kd,a,!0));a.i.subscribe("screenChange",(0,g.x)(function(){this.N("onlineScreenChange")},a))},j7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=d5(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.Ux("yt-remote-automatic-screen-cache",(0,g.ee)(a.o,Y4)));n7(a);a.u[b.uuid]=b.id;g.Ux("yt-remote-device-id-map",a.u,31536E3);return b},n7=function(a){a.u=g.Vx("yt-remote-device-id-map")||{}},o7=function(a,b,c){g.O.call(this);
this.R=c;this.D=a;this.i=b;this.l=null},p7=function(a,b){S6(a.R,b)},r7=function(a,b){o7.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.w=(0,g.x)(this.cM,this);this.u=(0,g.x)(this.zK,this);this.o=g.Bo((0,g.x)(function(){q7(this,null)},this),12E4)},pqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Bj(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ia,(0,g.x)(function(){p7(this,"Failed to send message: getMdxSessionStatus.")},a)):p7(a,"Sending yt message without session: "+g.Bj(b))},q7=function(a,b){g.Do(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.x)(a.Zm,a),d=(0,g.x)(a.Md,a);a.Mu(b,c,d,5)}}else a.Md(Error("Waiting for session status timed out."))},s7=function(a,b,c){o7.call(this,a,b,"DialSession");
this.o=this.C=null;this.G="";this.M=c;this.u=null;this.B=g.Ia;this.w=NaN;this.I=(0,g.x)(this.fM,this);this.g=g.Ia},t7=function(a){a.g=a.D.Vz(a.G,a.i.label,a.i.friendlyName,(0,g.x)(function(b){this.g=g.Ia;
this.Zm(b)},a),(0,g.x)(function(b){this.g=g.Ia;
this.Md(b)},a))},u7=function(a){var b={};
b.pairingCode=a.G;b.theme=a.M;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}o5()&&(b.env_useStageMdx=1);return g.Bf(b)},v7=function(a,b){o7.call(this,a,b,"ManualSession");
this.g=g.Bo((0,g.x)(this.Wh,this,null),150)},w7=function(a,b,c,d){g.O.call(this);
this.i=a;this.B=b||"233637DE";this.w=c||"cl";this.C=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.x)(this.fJ,this)},x7=function(a,b){return b?g.Ya(a.l,function(c){return X4(b,c.label)},a):null},y7=function(a){S6("Controller",a)},O6=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},z7=function(a){return a.u||!!a.l.length||!!a.g},A7=function(a,b,c){b!=a.g&&(g.Ai(a.g),(a.g=b)?(c?a.N("yt-remote-cast2-receiver-resumed",b.i):a.N("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.x)(a.Ux,a,b)),b.l?a.N("yt-remote-cast2-session-change",b.l):c&&a.g.Wh(null)):a.N("yt-remote-cast2-session-change",null))},B7=function(a){var b=a.i.Uz(),c=a.g&&a.g.i;
a=(0,g.ee)(b,function(d){c&&X4(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=x7(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},tqa=function(a,b,c,d,e,f,k){qqa()?rqa(b,e,f,k)&&(D7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?E7(a,c):(window.__onGCastApiAvailable=function(l,m){l?E7(a,c):(F7("Failed to load cast API: "+m),G7(!1),D7(!1),U4("yt-remote-cast-available"),U4("yt-remote-cast-receiver"),H7(),c(!1))},d?g.Oo("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?Ypa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?t5():(u5(),s5(sqa.map(Wpa))))):C7("Cannot initialize because not running Chrome")},H7=function(){C7("dispose");
var a=I7();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);J7(!1);g.Jo(K7);K7.length=0},L7=function(){return!!g.Vx("yt-remote-cast-installed")},M7=function(){var a=g.Vx("yt-remote-cast-receiver");
return a?a.friendlyName:null},N7=function(){C7("clearCurrentReceiver");
U4("yt-remote-cast-receiver")},O7=function(){return L7()?I7()?I7().getCastSession():(F7("getCastSelector: Cast is not initialized."),null):(F7("getCastSelector: Cast API is not installed!"),null)},Q7=function(){L7()?I7()?P7()?(C7("Requesting cast selector."),I7().requestSession()):(C7("Wait for cast API to be ready to request the session."),K7.push(g.Io("yt-remote-cast2-api-ready",Q7))):F7("requestCastSelector: Cast is not initialized."):F7("requestCastSelector: Cast API is not installed!")},R7=function(a,
b){P7()?I7().setConnectedScreenStatus(a,b):F7("setConnectedScreenStatus called before ready.")},qqa=function(){var a=0<=g.Kb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Bs||a},uqa=function(a,b){I7().init(a,b)},rqa=function(a,b,c,d){var e=!1;
I7()||(a=new w7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Ux("yt-remote-cast-available",f);T4("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){C7("onReceiverSelected: "+f.friendlyName);
g.Ux("yt-remote-cast-receiver",f);T4("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){C7("onReceiverResumed: "+f.friendlyName);
g.Ux("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){C7("onSessionChange: "+$4(f));
f||U4("yt-remote-cast-receiver");T4("yt-remote-cast2-session-change",f)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
C7("cloudview.createSingleton_: "+e);return e},I7=function(){return g.w("yt.mdx.remote.cloudview.instance_")},E7=function(a,b){G7(!0);
D7(!1);uqa(a,function(c){c?(J7(!0),g.Lo("yt-remote-cast2-api-ready")):(F7("Failed to initialize cast API."),G7(!1),U4("yt-remote-cast-available"),U4("yt-remote-cast-receiver"),H7());b(c)})},C7=function(a){S6("cloudview",a)},F7=function(a){S6("cloudview",a)},G7=function(a){C7("setCastInstalled_ "+a);
g.Ux("yt-remote-cast-installed",a)},P7=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},J7=function(a){C7("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},D7=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},S7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.w=this.B=0;this.g=null;this.hasNext=this.xe=!1;this.D=this.C=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},T7=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.xe=!1;a.hasNext=!1;a.B=0;a.w=(0,g.A)();a.o=0;a.i=0;a.C=0;a.D=0;a.l=NaN;a.u=!1},U7=function(a){return 1==a.playerState?((0,g.A)()-a.w)/1E3:0},V7=function(a,b){a.B=b;
a.w=(0,g.A)()},W7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.A)()-a.w)/1E3+a.B;
case -1E3:return 0}return a.B},X7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&T7(a)},Y7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.g);b.hasPrevious=a.xe;b.hasNext=a.hasNext;b.playerTime=a.B;b.playerTimeAt=a.w;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.C;b.loadedTime=a.D;b.liveIngestionTime=a.l;return b},a8=function(a,b){g.O.call(this);
this.g=0;this.o=a;this.w=[];this.u=new G6;this.l=this.i=null;this.D=(0,g.x)(this.cH,this);this.B=(0,g.x)(this.Xj,this);this.C=(0,g.x)(this.bH,this);this.G=(0,g.x)(this.oH,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Wr,this),Z7(this))):c=3;0!=c&&(b?this.Wr(c):g.Bo((0,g.x)(function(){this.Wr(c)},this),0));
var d=O7();d&&$7(this,d);this.subscribe("yt-remote-cast2-session-change",this.G)},b8=function(a){return new S7(a.o.getPlayerContextData())},Z7=function(a){(0,g.z)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.w.push(this.o.subscribe(b,g.Ra(this.cJ,b),this))},a)},c8=function(a){(0,g.z)(a.w,function(b){this.o.unsubscribeByKey(b)},a);
a.w.length=0},d8=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},f8=function(a,b,c){var d=b8(a);
V7(d,c);-1E3!=d.playerState&&(d.playerState=b);e8(a,d)},g8=function(a,b,c){a.o.sendMessage(b,c)},e8=function(a,b){c8(a);
a.o.setPlayerContextData(Y7(b));Z7(a)},$7=function(a,b){a.l&&(a.l.removeUpdateListener(a.D),a.l.removeMediaListener(a.B),a.Xj(null));
a.l=b;a.l&&(S6("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.D),a.l.addMediaListener(a.B),a.l.media.length&&a.Xj(a.l.media[0]))},h8=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=b8(a);b.contentId!=d.videoId&&S6("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;V7(d,a.i.getEstimatedTime());e8(a,d)}else S6("CP","No cast media video. Ignoring state update.")},i8=function(a,b,c){return(0,g.x)(function(d){this.Gb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Gb("Retrying "+b+" using MDx browser channel."),g8(this,b,c))},a)},j8=function(a,b,c){g.O.call(this);
this.u=NaN;this.I=!1;this.C=this.B=this.D=this.G=NaN;this.R=[];this.o=this.w=this.l=this.Oa=this.g=null;this.P=a;this.R.push(g.Yq(window,"beforeunload",(0,g.x)(this.YB,this)));this.i=[];this.Oa=new S7;this.M=b.id;this.g=vqa(this,c);this.g.subscribe("handlerOpened",this.gH,this);this.g.subscribe("handlerClosed",this.dH,this);this.g.subscribe("handlerError",this.eH,this);this.g.subscribe("handlerMessage",this.fH,this);fqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Oa.videoId;
g.ZK()&&g.Ux("yt-remote-session-video-id",d)},this)},k8=function(a){S6("conn",a)},vqa=function(a,b){return new I6(M6(a.P,"/bc"),b)},l8=function(a,b){a.N("proxyStateChange",b)},wqa=function(a){a.u=g.Bo((0,g.x)(function(){k8("Connecting timeout");
this.Ah(1)},a),2E4)},m8=function(a){g.Do(a.u);
a.u=NaN},n8=function(a){g.Do(a.G);
a.G=NaN},xqa=function(a){o8(a);
a.D=g.Bo((0,g.x)(function(){p8(this,"getNowPlaying")},a),2E4)},o8=function(a){g.Do(a.D);
a.D=NaN},r8=function(a,b){b&&(m8(a),n8(a));
b==(K6(a.g)&&isNaN(a.u))?b&&(l8(a,1),p8(a,"getSubtitlesTrack")):b?(a.Ku()&&a.Oa.reset(),l8(a,1),p8(a,"getNowPlaying"),q8(a)):a.Ah(1)},yqa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Oa.videoId&&(g.Zb(b.params)?a.Oa.g=null:a.Oa.g=b.params,a.N("remotePlayerChange"))},s8=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Oa.listId=b.params.listId||a.Oa.listId;X7(a.Oa,c,d);a.N("remoteQueueChange")},zqa=function(a,b){b.params=b.params||{};
s8(a,b);t8(a,b);a.N("autoplayDismissed")},t8=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
V7(a.Oa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Oa.playerState&&(c=-1E3);a.Oa.playerState=c;c=Number(b.params.loadedTime);a.Oa.D=isNaN(c)?0:c;c=Number(b.params.duration);a.Oa.C=isNaN(c)?0:c;c=a.Oa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Oa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Oa.playerState?xqa(a):o8(a);a.N("remotePlayerChange")},Aqa=function(a,b){if(-1E3!=
a.Oa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Oa.playerState=c;c=parseInt(b.params.currentTime,10);V7(a.Oa,isNaN(c)?0:c);a.N("remotePlayerChange")}},Bqa=function(a,b){var c="true"==b.params.muted;
a.Oa.volume=parseInt(b.params.volume,10);a.Oa.muted=c;a.N("remotePlayerChange")},Cqa=function(a,b){a.w=b.params.videoId;
a.N("nowAutoplaying",parseInt(b.params.timeout,10))},Dqa=function(a,b){var c="true"==b.params.hasNext;
a.Oa.xe="true"==b.params.hasPrevious;a.Oa.hasNext=c;a.N("previousNextChange")},q8=function(a){g.Do(a.C);
a.C=g.Bo((0,g.x)(a.Ah,a,1),864E5)},p8=function(a,b,c){c?k8("Sending: action="+b+", params="+g.Bj(c)):k8("Sending: action="+b);
a.g.sendMessage(b,c)},u8=function(a){W6.call(this,"ScreenServiceProxy");
this.Rc=a;this.i=[];this.i.push(this.Rc.$_s("screenChange",(0,g.x)(this.aM,this)));this.i.push(this.Rc.$_s("onlineScreenChange",(0,g.x)(this.FI,this)))},Iqa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.to("MDX_CONFIG")||b;Npa();i5();v8||(v8=new L6(b?b.loungeApiHost:void 0),o5()&&(v8.g="/api/loungedev"));w8||(w8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",w8,void 0));Eqa();var c=x8();if(!c){var d=new i7(v8);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=x8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);tqa(a,d,function(m){m?y8()&&R7(y8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){T4("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),z8("Initializing: "+g.Bj(b)),A8.push(g.Io("yt-remote-cast2-availability-change",function(){T4("yt-remote-receiver-availability-change")})),A8.push(g.Io("yt-remote-cast2-receiver-selected",function(){B8(null);
T4("yt-remote-auto-connect","cast-selector-receiver")})),A8.push(g.Io("yt-remote-cast2-receiver-resumed",function(){T4("yt-remote-receiver-resumed","cast-selector-receiver")})),A8.push(g.Io("yt-remote-cast2-session-change",Fqa)),A8.push(g.Io("yt-remote-connection-change",function(m){m?R7(y8(),"YouTube TV"):C8()||(R7(null,null),N7())})),a=D8(),b.isAuto&&(a.id+="#dial"),g.qp("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),z8(" -- with channel params: "+
g.Bj(a)),Gqa(a),c.start(),y8()||Hqa())},Jqa=function(){var a=E8();
L7()&&g.Vx("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},E8=function(){var a=x8().Rc.$_gos();
var b=F8();b&&G8()&&(c5(a,b)||a.push(b));return Spa(a)},H8=function(){var a=Kqa();
!a&&L7()&&M7()&&(a={key:"cast-selector-receiver",name:M7()});return a},Kqa=function(){var a=E8(),b=F8();
b||(b=C8());return g.Ya(a,function(c){return b&&X4(b,c.key)?!0:!1})},F8=function(){var a=y8();
if(!a)return null;var b=x8().Kd();return d5(b,a)},Fqa=function(a){z8("remote.onCastSessionChange_: "+$4(a));
if(a){var b=F8();b&&b.id==a.id?R7(b.id,"YouTube TV"):(b&&I8(),J8(a,1))}else G8()&&I8()},I8=function(){P7()?I7().stopSession():F7("stopSession called before API ready.");
var a=G8();a&&(a.disconnect(1),K8(null))},L8=function(){var a=G8();
return!!a&&3!=a.getProxyState()},z8=function(a){S6("remote",a)},x8=function(){if(!M8){var a=g.w("yt.mdx.remote.screenService_");
M8=a?new u8(a):null}return M8},y8=function(){return g.w("yt.mdx.remote.currentScreenId_")},N8=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},O8=function(){return g.w("yt.mdx.remote.connectData_")},B8=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},G8=function(){return g.w("yt.mdx.remote.connection_")},K8=function(a){var b=G8();
B8(null);a||N8("");g.Ga("yt.mdx.remote.connection_",a,void 0);w8&&((0,g.z)(w8,function(c){c(a)}),w8.length=0);
b&&!a?T4("yt-remote-connection-change",!1):!b&&a&&T4("yt-remote-connection-change",!0)},C8=function(){var a=g.ZK();
if(!a)return null;var b=x8().Kd();return d5(b,a)},J8=function(a,b){F8()&&F8();
if(P8)Q8=a;else{N8(a.id);var c=new j8(v8,a,D8());c.connect(b,O8());c.subscribe("beforeDisconnect",function(d){T4("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){G8()&&K8(null)});
K8(c)}},Hqa=function(){var a=C8();
a?(z8("Resume connection to: "+$4(a)),J8(a,0)):(m5(),N7(),z8("Skipping connecting because no session screen found."))},Eqa=function(){var a=D8();
if(g.Zb(a)){a=h5();var b=g.Vx("yt-remote-session-name")||"",c=g.Vx("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},D8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},Gqa=function(a){a?(g.Ux("yt-remote-session-app",a.app),g.Ux("yt-remote-session-name",a.name)):(U4("yt-remote-session-app"),U4("yt-remote-session-name"));
g.Ga("yt.mdx.remote.channelParams_",a,void 0)},R8=function(a,b,c){g.F.call(this);
this.u=a;this.i=b;this.l=new g.Is(this);g.H(this,this.l);this.l.J(b,"onCaptionsTrackListChanged",this.aI);this.l.J(b,"captionschanged",this.aH);this.l.J(b,"captionssettingschanged",this.gz);this.l.J(b,"videoplayerreset",this.an);this.l.J(b,"mdxautoplaycancel",this.ZA);this.P=this.l.J(b,"onVolumeChange",this.Cx);this.C=!1;this.g=c;c.subscribe("proxyStateChange",this.Qx,this);c.subscribe("remotePlayerChange",this.Zj,this);c.subscribe("remoteQueueChange",this.an,this);c.subscribe("autoplayUpNext",this.rx,
this);c.subscribe("previousNextChange",this.Nx,this);c.subscribe("nowAutoplaying",this.Jx,this);c.subscribe("autoplayDismissed",this.qx,this);this.suggestion=null;this.D=new g.tt(64);this.o=new g.I(this.ez,500,this);g.H(this,this.o);this.w=new g.I(this.fz,1E3,this);g.H(this,this.w);this.I=new v5(this.FL,0,this);g.H(this,this.I);this.B={};this.R=new g.I(this.Hz,1E3,this);g.H(this,this.R);this.G=new g.hl(this.xE,1E3,this);g.H(this,this.G);this.M=g.Ia;this.gz();this.an();this.Zj()},S8=function(a,b){var c=
a.u,d=a.i.getVideoData().lengthSeconds;
c.R=b||0;c.player.N("progresssync",b,d)},U8=function(a){S8(a,0);
a.o.stop();T8(a,new g.tt(64))},W8=function(a,b){if(V8(a)&&!a.C){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.ec(c,b));a.g.Vy(a.i.getVideoData(1).videoId,c);a.B=b8(a.g).g}},X8=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Qa;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.ze,P4(c));T8(a,new g.tt(1))},Y8=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{wP:1});
c&&c.length?(a.i.setOption("captions","track",b),a.C=!1):(a.i.loadModule("captions"),a.C=!0)}else a.i.setOption("captions","track",{})},V8=function(a){return b8(a.g).videoId==a.i.getVideoData(1).videoId},T8=function(a,b){a.w.stop();
var c=a.D;if(!g.At(c,b)){var d=g.R(b,2);d!=g.R(a.D,2)&&g.SR(a.i.app,d);a.D=b;Z8(a.u,c,b)}},$8=function(){g.T.call(this,{A:"div",
F:"ytp-mdx-popup-dialog",K:{role:"dialog"},H:[{A:"div",F:"ytp-mdx-popup-dialog-inner-content",H:[{A:"div",F:"ytp-mdx-popup-title",T:"You're signed out"},{A:"div",F:"ytp-mdx-popup-description",T:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{A:"div",F:"ytp-mdx-privacy-popup-buttons",H:[{A:"button",U:["ytp-button","ytp-mdx-privacy-popup-cancel"],T:"Cancel"},{A:"button",U:["ytp-button","ytp-mdx-privacy-popup-confirm"],
T:"Confirm"}]}]}]});this.l=new g.eL(this,250);g.H(this,this.l);this.B=this.i["ytp-mdx-privacy-popup-cancel"];this.J(this.B,"click",this.o);this.u=this.i["ytp-mdx-privacy-popup-confirm"];this.J(this.u,"click",this.w)},b9=function(a){g.T.call(this,{A:"div",
F:"ytp-remote",H:[{A:"div",F:"ytp-remote-display-status",H:[{A:"div",F:"ytp-remote-display-status-icon",H:[g.gL()]},{A:"div",F:"ytp-remote-display-status-text",T:"{{statustext}}"}]}]});this.l=new g.eL(this,250);g.H(this,this.l);this.o=a;this.J(a,"presentingplayerstatechange",this.u);a9(this,g.bK(a))},a9=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.R(b,128)?g.LL("Error on $RECEIVER_NAME",c):g.Bt(b)||g.R(b,4)?g.LL("Playing on $RECEIVER_NAME",c):g.LL("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},c9=function(a,b){g.HN.call(this,"Play on",0,a,b);
this.l=a;this.B={};this.J(a,"onMdxReceiversChange",this.I);this.J(a,"presentingplayerstatechange",this.I);this.I()},d9=function(a){g.QO.call(this,a);
this.i={key:b5(),name:"This computer"};this.u=null;this.o=[];this.M=this.g=null;this.G=[this.i];this.l=this.i;this.B=new g.tt(64);this.R=0;this.D=-1;this.w=null;if(!g.Yy(this.player.L())){a=this.player;var b=g.JC(a);b&&(b=b.Im())&&(b=new c9(a,b),g.H(this,b));b=new b9(a);g.H(this,b);g.tK(a,b.element,4);this.w=new $8;g.H(this,this.w);g.tK(a,this.w.element,4);this.I=!!C8()}this.C=null},e9=function(a){a.C&&(a.player.removeEventListener("presentingplayerstatechange",a.C),a.C=null)},Z8=function(a,b,c){a.B=
c;
a.player.N("presentingplayerstatechange",new g.$C(c,b))},f9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)I8();
else{var c;(c=!g.P(a.player.L().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.to("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.to("SESSION_INDEX")&&!g.to("LOGGED_IN")))||a.I||!a.w);if(c?0:"WEB"==a.player.L().deviceParams.c||"WEB_EMBEDDED_PLAYER"==a.player.L().deviceParams.c)g.Bt(g.bK(a.player))?a.player.pauseVideo():(a.C=(0,g.x)(a.EK,a),a.player.addEventListener("presentingplayerstatechange",a.C)),a.w&&a.w.l.show(),G8()||(P8=!0);a.l=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);
var e=c.videoId;if(d||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.ra(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.ze,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=P4(c))&&(d.locationInfo=c);c=d}else c=null;z8("Connecting to: "+g.Bj(b));"cast-selector-receiver"==b.key?(B8(c||null),P7()?I7().setLaunchParams(c||null):F7("setLaunchParams called before ready.")):
!c&&L8()&&y8()==b.key?T4("yt-remote-connection-change",!0):(I8(),B8(c||null),c=x8().Kd(),(c=d5(c,b.key))&&J8(c,1))}},P5={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},O5={"'":"\\'"},Lqa={},Qpa={AM:"atp",OO:"ska",DO:"que",fO:"mus",NO:"sus",xN:"dsp",KO:"seq"};
V4.prototype.Rf=function(){var a=new V4({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var n5,g5="",Xpa=p5("loadCastFramework")||p5("loadCastApplicationFramework"),sqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.Ta(v5,g.F);g.h=v5.prototype;g.h.UB=function(a){this.o=arguments;this.g=!1;this.za?this.l=(0,g.A)()+this.Sc:this.za=g.fl(this.u,this.Sc)};
g.h.stop=function(){this.za&&(g.u.clearTimeout(this.za),this.za=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.w.apply(null,this.o)))};
g.h.V=function(){this.stop();v5.wb.V.call(this)};
g.h.VB=function(){this.l?(this.za=g.fl(this.u,this.l-(0,g.A)()),this.l=null):(this.za=null,this.i?this.g=!0:(this.g=!1,this.w.apply(null,this.o)))};x5.prototype.stringify=function(a){return g.u.JSON.stringify(a,void 0)};
x5.prototype.parse=function(a){return g.u.JSON.parse(a,void 0)};y5.prototype.g=null;y5.prototype.getOptions=function(){var a;(a=this.g)||(a={},A5(this)&&(a[0]=!0,a[1]=!0),a=this.g=a);return a};var g9;g.Ta(z5,y5);g9=new z5;g.h=C5.prototype;g.h.Mg=null;g.h.ne=!1;g.h.Fi=null;g.h.Tr=null;g.h.oi=null;g.h.Jh=null;g.h.Kf=null;g.h.rg=null;g.h.eh=null;g.h.pc=null;g.h.Dk=0;g.h.re=null;g.h.Mn=null;g.h.cg=null;g.h.pj=-1;g.h.Qy=!0;g.h.Bg=!1;g.h.kp=0;g.h.gn=null;var J5={},H5={};g.h=C5.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.QK=function(a){a=a.target;var b=this.gn;b&&3==f6(a)?b.Sl():this.Pz(a)};
g.h.Pz=function(a){try{if(a==this.pc)a:{var b=f6(this.pc),c=this.pc.w,d=this.pc.getStatus();if(g.Jd&&!g.od(10)||g.Ld&&!g.ld("420+")){if(4>b)break a}else if(3>b||3==b&&!g.$f&&!j6(this.pc))break a;this.Bg||4!=b||7==c||(8==c||0>=d?this.g.me(3):this.g.me(2));T5(this);var e=this.pc.getStatus();this.pj=e;var f=j6(this.pc);(this.ne=200==e)?(4==b&&L5(this),this.u?(N5(this,b,f),g.$f&&this.ne&&3==b&&(this.ba.ea(this.i,"tick",this.KK),this.i.start())):K5(this,f),this.ne&&!this.Bg&&(4==b?this.g.Xm(this):(this.ne=
!1,G5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.cg=3,I5(13)):(this.cg=0,I5(14)),L5(this),M5(this))}}catch(k){this.pc&&j6(this.pc)}finally{}};
g.h.KK=function(){var a=f6(this.pc),b=j6(this.pc);this.Dk<b.length&&(T5(this),N5(this,a,b),this.ne&&4!=a&&G5(this))};
g.h.fK=function(a){S5((0,g.x)(this.eK,this,a),0)};
g.h.eK=function(a){this.Bg||(T5(this),K5(this,a),G5(this))};
g.h.Xx=function(a){S5((0,g.x)(this.dK,this,a),0)};
g.h.dK=function(a){this.Bg||(L5(this),this.ne=a,this.g.Xm(this),this.g.me(4))};
g.h.cancel=function(){this.Bg=!0;L5(this)};
g.h.oK=function(){this.Fi=null;var a=(0,g.A)();0<=a-this.Tr?(2!=this.Jh&&this.g.me(3),L5(this),this.cg=2,I5(18),M5(this)):R5(this,this.Tr-a)};
g.h.getLastError=function(){return this.cg};g.h=X5.prototype;g.h.ip=null;g.h.Ad=null;g.h.hn=!1;g.h.Su=null;g.h.Dl=null;g.h.Mp=null;g.h.jp=null;g.h.Zd=null;g.h.qf=-1;g.h.oj=null;g.h.Pi=null;g.h.connect=function(a){this.jp=a;a=Y5(this.g,null,this.jp);I5(3);this.Su=(0,g.A)();var b=this.g.C;null!=b?(this.oj=b[0],(this.Pi=b[1])?(this.Zd=1,Z5(this)):(this.Zd=2,a6(this))):(O4(a,"MODE","init"),this.Ad=new C5(this,void 0,void 0,void 0),this.Ad.Mg=this.ip,F5(this.Ad,a,!1,null,!0),this.Zd=0)};
g.h.aB=function(a){if(a)this.Zd=2,a6(this);else{I5(4);var b=this.g;b.we=b.Qf.qf;D6(b,9)}a&&this.me(2)};
g.h.Ho=function(a){return this.g.Ho(a)};
g.h.abort=function(){this.Ad&&(this.Ad.cancel(),this.Ad=null);this.qf=-1};
g.h.Ru=function(){return!1};
g.h.Rx=function(a,b){this.qf=a.pj;if(0==this.Zd)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.we=this.qf;D6(c,2);return}this.oj=c[0];this.Pi=c[1]}else c=this.g,c.we=this.qf,D6(c,2);else if(2==this.Zd)if(this.hn)I5(7),this.Mp=(0,g.A)();else if("11111"==b){if(I5(6),this.hn=!0,this.Dl=(0,g.A)(),c=this.Dl-this.Su,!g.Jd||g.od(10)||500>c)this.qf=200,this.Ad.cancel(),I5(12),$5(this.g,this,!0)}else I5(8),this.Dl=this.Mp=(0,g.A)(),this.hn=!1};
g.h.Xm=function(){this.qf=this.Ad.pj;if(this.Ad.ne)0==this.Zd?this.Pi?(this.Zd=1,Z5(this)):(this.Zd=2,a6(this)):2==this.Zd&&((!g.Jd||g.od(10)?!this.hn:200>this.Mp-this.Dl)?(I5(11),$5(this.g,this,!1)):(I5(12),$5(this.g,this,!0)));else{0==this.Zd?I5(9):2==this.Zd&&I5(10);var a=this.g;this.Ad.getLastError();a.we=this.qf;D6(a,2)}};
g.h.pk=function(){return this.g.pk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.me=function(a){this.g.me(a)};g.Ta(b6,g.uk);var bqa=/^https?$/i,Mqa=["POST","PUT"];g.h=b6.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.D+"; newUri="+a);b=b?b.toUpperCase():"GET";this.D=a;this.o="";this.w=0;this.W=b;this.P=!1;this.l=!0;this.g=this.M?B5(this.M):B5(g9);this.R=this.M?this.M.getOptions():g9.getOptions();this.g.onreadystatechange=(0,g.x)(this.Tu,this);try{S4(g6(this,"Opening Xhr")),this.aa=!0,this.g.open(b,String(a),!0),this.aa=!1}catch(f){S4(g6(this,"Error opening Xhr: "+f.message));e6(this,f);return}a=c||"";
var e=this.headers.clone();d&&Lpa(d,function(f,k){e.set(k,f)});
d=g.Ya(e.Wd(),aqa);c=g.u.FormData&&a instanceof g.u.FormData;!g.ab(Mqa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.X&&(this.g.responseType=this.X);"withCredentials"in this.g&&this.g.withCredentials!==this.S&&(this.g.withCredentials=this.S);try{i6(this),0<this.B&&(this.I=$pa(this.g),S4(g6(this,"Will abort after "+this.B+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.B,this.g.ontimeout=(0,g.x)(this.Uu,this)):this.G=g.fl(this.Uu,this.B,this)),S4(g6(this,"Sending request")),this.C=!0,this.g.send(a),this.C=!1}catch(f){S4(g6(this,"Send error: "+f.message)),e6(this,f)}};
g.h.Uu=function(){"undefined"!=typeof g.fZ&&this.g&&(this.o="Timed out after "+this.B+"ms, aborting",this.w=8,g6(this,this.o),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.l&&(g6(this,"Aborting"),this.l=!1,this.u=!0,this.g.abort(),this.u=!1,this.w=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),d6(this))};
g.h.V=function(){this.g&&(this.l&&(this.l=!1,this.u=!0,this.g.abort(),this.u=!1),d6(this,!0));b6.wb.V.call(this)};
g.h.Tu=function(){this.fa()||(this.aa||this.C||this.u?h6(this):this.eJ())};
g.h.eJ=function(){h6(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<f6(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.Da(this.o)?this.o:String(this.o)};g.h=k6.prototype;g.h.bj=null;g.h.td=null;g.h.Nb=null;g.h.hp=null;g.h.Fl=null;g.h.ot=null;g.h.Tl=null;g.h.Uj=0;g.h.uG=0;g.h.Pc=null;g.h.Xf=null;g.h.bf=null;g.h.Fg=null;g.h.Qf=null;g.h.Kn=null;g.h.Vh=-1;g.h.Ev=-1;g.h.we=-1;g.h.Ch=0;g.h.wh=0;g.h.Cg=8;var E6=new g.uk;g.Ta(l6,g.Xj);g.Ta(m6,g.Xj);g.Ta(n6,g.Xj);g.h=k6.prototype;g.h.connect=function(a,b,c,d,e){I5(0);this.hp=b;this.bj=c||{};d&&g.Ca(e)&&(this.bj.OSID=d,this.bj.OAID=e);this.w?(S5((0,g.x)(this.Ot,this,a),100),t6(this)):this.Ot(a)};
g.h.Ot=function(a){this.Qf=new X5(this);this.Qf.ip=null;this.Qf.i=this.u;this.Qf.connect(a)};
g.h.Ru=function(){return 0==this.g};
g.h.Wx=function(a){this.Xf=null;y6(this,a)};
g.h.Vx=function(){this.bf=null;this.Nb=new C5(this,this.l,"rpc",this.B);this.Nb.Mg=null;this.Nb.kp=0;var a=this.ot.clone();M4(a,"RID","rpc");M4(a,"SID",this.l);M4(a,"CI",this.Kn?"0":"1");M4(a,"AID",this.Vh);p6(this,a);if(!g.Jd||g.od(10))M4(a,"TYPE","xmlhttp"),F5(this.Nb,a,!0,this.Tl,!1);else{M4(a,"TYPE","html");var b=this.Nb,c=!!this.Tl;b.Jh=3;b.Kf=N4(a.clone());Q5(b,c)}};
g.h.Rx=function(a,b){if(0!=this.g&&(this.Nb==a||this.td==a))if(this.we=a.pj,this.td==a&&3==this.g)if(7<this.Cg){try{var c=this.u.parse(b)}catch(f){c=null}if(g.La(c)&&3==c.length)if(0==c[0])a:{if(!this.bf){if(this.Nb)if(this.Nb.oi+3E3<this.td.oi)u6(this),this.Nb.cancel(),this.Nb=null;else break a;B6(this);I5(19)}}else this.Ev=c[1],0<this.Ev-this.Vh&&37500>c[2]&&this.Kn&&0==this.wh&&!this.Fg&&(this.Fg=S5((0,g.x)(this.WG,this),6E3));else D6(this,11)}else b!=Lqa.YM.g&&D6(this,11);else if(this.Nb==a&&
u6(this),!g.yb(b)){c=this.u.parse(b);g.La(c);for(var d=0;d<c.length;d++){var e=c[d];this.Vh=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.Tl=e[2],e=e[3],null!=e?this.Cg=e:this.Cg=6,this.g=3,this.Pc&&this.Pc.It(),this.ot=Y5(this,this.pk()?this.Tl:null,this.hp),z6(this)):"stop"==e[0]&&D6(this,7):3==this.g&&("stop"==e[0]?D6(this,7):"noop"!=e[0]&&this.Pc&&this.Pc.Ht(e),this.wh=0)}}};
g.h.WG=function(){null!=this.Fg&&(this.Fg=null,this.Nb.cancel(),this.Nb=null,B6(this),I5(20))};
g.h.Xm=function(a){if(this.Nb==a){u6(this);this.Nb=null;var b=2}else if(this.td==a)this.td=null,b=1;else return;this.we=a.pj;if(0!=this.g)if(a.ne)1==b?(b=(0,g.A)()-a.oi,E6.dispatchEvent(new m6(E6,a.eh?a.eh.length:0,b,this.Ch)),s6(this),this.o.length=0):z6(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.we)){if(d=1==b)this.td||this.Xf||1==this.g||2<=this.Ch?d=!1:(this.Xf=S5((0,g.x)(this.Wx,this,a),A6(this,this.Ch)),this.Ch++,d=!0);d=!(d||2==b&&B6(this))}if(d)switch(c){case 1:D6(this,
5);break;case 4:D6(this,10);break;case 3:D6(this,6);break;case 7:D6(this,12);break;default:D6(this,2)}}};
g.h.uB=function(a){if(!g.ab(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.wL=function(a){a?I5(2):(I5(1),C6(this,8))};
g.h.Ho=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new b6;a.S=!1;return a};
g.h.isActive=function(){return!!this.Pc&&this.Pc.isActive(this)};
g.h.me=function(a){E6.dispatchEvent(new n6(E6,a))};
g.h.pk=function(){return!(!g.Jd||g.od(10))};
g.h=F6.prototype;g.h.It=function(){};
g.h.Ht=function(){};
g.h.Gt=function(){};
g.h.Ao=function(){};
g.h.uu=function(){return{}};
g.h.isActive=function(){return!0};g.h=G6.prototype;g.h.isEmpty=function(){return g.bb(this.g)&&g.bb(this.i)};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.ab(this.g,a)||g.ab(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.rna)(b,a);0<=c?(g.db(b,c),b=!0):b=!1;return b||g.eb(this.i,a)};
g.h.wd=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};g.Ta(H6,g.F);g.h=H6.prototype;g.h.WJ=function(){this.Sc=Math.min(3E5,2*this.Sc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Sc+15E3*Math.random();g.an(this.g,a);this.i=(0,g.A)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Sc=5E3};g.Ta(I6,F6);g.h=I6.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.yf=function(a){return this.l.Ng(a)};
g.h.N=function(a,b){return this.l.N.apply(this.l,arguments)};
g.h.dispose=function(){this.bb||(this.bb=!0,g.Ai(this.l),J6(this),g.Ai(this.i),this.i=null)};
g.h.fa=function(){return this.bb};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.D="";this.i.stop();this.u=a||null;this.o=b||0;a=this.G+"/test";b=this.G+"/bind";var d=new k6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Pc=null);d.Pc=this;this.g=d;e?this.g.connect(a,b,this.w,e.l,e.Vh):c?this.g.connect(a,b,this.w,c.sessionId,c.arrayId):this.g.connect(a,b,this.w)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.B.push(c):K6(this)&&v6(this.g,c)};
g.h.It=function(){this.i.reset();this.u=null;this.o=0;if(this.B.length){var a=this.B;this.B=[];for(var b=0,c=a.length;b<c;++b)v6(this.g,a[b])}this.N("handlerOpened")};
g.h.Gt=function(a){var b=2==a&&401==this.g.we;4==a||b||this.i.start();this.N("handlerError",a)};
g.h.Ao=function(a){if(!this.i.isActive())this.N("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.B.push(d)}};
g.h.uu=function(){var a={v:2};this.D&&(a.gsessionid=this.D);0!=this.o&&(a.ui=""+this.o);0!=this.C&&(a.ui=""+this.C);this.u&&g.ec(a,this.u);return a};
g.h.Ht=function(a){"S"==a[0]?this.D=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),r6(this.g)):this.N("handlerMessage",new dqa(a[0],a[1]))};
g.h.aL=function(){this.i.isActive();var a=this.g,b=0;a.Nb&&b++;a.td&&b++;0==b&&this.connect(this.u,this.o)};L6.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
L6.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
L6.prototype.u=function(a){a(Error("request timed out"))};var jqa=(0,g.A)(),Q6=null,U6=Array(50),T6=-1,V6=!1;g.Ta(W6,g.O);W6.prototype.Kd=function(){return this.g};
W6.prototype.contains=function(a){return!!c5(this.g,a)};
W6.prototype.get=function(a){return a?d5(this.g,a):null};
W6.prototype.info=function(a){S6(this.B,a)};g.r(Y6,g.O);g.h=Y6.prototype;g.h.start=function(){!this.g&&isNaN(this.za)&&this.Tz()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.za)||(g.Do(this.za),this.za=NaN)};
g.h.V=function(){this.stop();g.O.prototype.V.call(this)};
g.h.Tz=function(){this.za=NaN;this.g=g.zp(M6(this.w,"/pairing/get_screen"),{method:"POST",rb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.x)(this.YL,this),onError:(0,g.x)(this.XL,this),Nd:(0,g.x)(this.ZL,this)})};
g.h.YL=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.N("pairingComplete",new W4(c))};
g.h.XL=function(a){this.g=null;a.status&&404==a.status?this.i>=h9.length?this.N("pairingFailed",Error("DIAL polling timed out")):(a=h9[this.i],this.za=g.Bo((0,g.x)(this.Tz,this),a),this.i++):this.N("pairingFailed",Error("Server error "+a.status))};
g.h.ZL=function(){this.g=null;this.N("pairingFailed",Error("Server not responding"))};
var h9=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ta($6,W6);g.h=$6.prototype;g.h.start=function(){Z6(this)&&this.N("screenChange");!g.Vx("yt-remote-lounge-token-expiration")&&a7(this);g.Do(this.i);this.i=g.Bo((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){Z6(this);X6(this,a);b7(this,!1);this.N("screenChange");b(a);a.token||a7(this)};
g.h.remove=function(a,b){var c=Z6(this);lqa(this,a)&&(b7(this,!1),c=!0);b(a);c&&this.N("screenChange")};
g.h.Gn=function(a,b,c,d){var e=Z6(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,b7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.N("screenChange")};
g.h.V=function(){g.Do(this.i);$6.wb.V.call(this)};
g.h.gC=function(a){Z6(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}b7(this,!b);b&&S6(this.B,"Missed "+b+" lounge tokens.")};
g.h.fC=function(a){S6(this.B,"Requesting lounge tokens failed: "+a)};g.r(d7,g.O);g.h=d7.prototype;g.h.start=function(){var a=parseInt(g.Vx("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.A)()-144E5<a?0:a)?g7(this):(this.o=(0,g.A)()+3E5,g.Ux("yt-remote-fast-check-period",this.o),this.gr())};
g.h.isEmpty=function(){return g.Zb(this.g)};
g.h.update=function(){c7("Updating availability on schedule.");var a=this.w(),b=g.Nb(this.g,function(c,d){return c&&!!d5(a,d)},this);
f7(this,b)};
g.h.V=function(){g.Do(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);g.O.prototype.V.call(this)};
g.h.gr=function(){g.Do(this.l);this.l=NaN;this.i&&this.i.abort();var a=h7(this);if(Q4(a)){var b=M6(this.u,"/pairing/get_screen_availability");this.i=N6(this.u,b,{lounge_token:g.Tb(a).join(",")},(0,g.x)(this.AJ,this,a),(0,g.x)(this.zJ,this))}else f7(this,{}),g7(this)};
g.h.AJ=function(a,b){this.i=null;var c=g.Tb(h7(this));if(g.sb(c,g.Tb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;f7(this,d);g7(this)}else this.Gb("Changing Screen set during request."),this.gr()};
g.h.zJ=function(a){this.Gb("Screen availability failed: "+a);this.i=null;g7(this)};
g.h.Gb=function(a){S6("OnlineScreenService",a)};g.Ta(i7,W6);g.h=i7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.N("screenChange"),this.i.isEmpty()||this.N("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.Gn=function(a,b,c,d){this.l.contains(a)?this.l.Gn(a,b,c,d):(a="Updating name of unknown screen: "+a.name,S6(this.B,a),d(Error(a)))};
g.h.Kd=function(a){return a?this.g:g.gb(this.g,(0,g.Vd)(this.o,function(b){return!this.contains(b)},this))};
g.h.Uz=function(){return(0,g.Vd)(this.Kd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.Vz=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new Y6(this.w,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.Ai(f);d(j7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.Ai(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.bM=function(a,b,c,d){g.zp(M6(this.w,"/pairing/get_screen"),{method:"POST",rb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new W4(f.screen||{});if(!k.name||l7(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);l7(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(j7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Nd:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.Ai(this.l);g.Ai(this.i);i7.wb.V.call(this)};
g.h.nC=function(){m7(this);this.N("screenChange");this.i.update()};
i7.prototype.dispose=i7.prototype.dispose;g.Ta(o7,g.O);g.h=o7.prototype;g.h.Zm=function(a){this.l=a;this.N("sessionScreen",this.l)};
g.h.Md=function(a){this.fa()||(a&&p7(this,""+a),this.l=null,this.N("sessionScreen",null))};
g.h.info=function(a){S6(this.R,a)};
g.h.Xz=function(){return null};
g.h.sr=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){p7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.sr("");o7.wb.V.call(this)};g.Ta(r7,o7);g.h=r7.prototype;g.h.rr=function(a){if(this.g){if(this.g==a)return;p7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.w);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.w);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);pqa(this)};
g.h.Wh=function(a){this.info("launchWithParams no-op for Cast: "+g.Bj(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.x)(function(){this.Md()},this),(0,g.x)(function(){this.Md(Error("Failed to stop receiver app."))},this)):this.Md(Error("Stopping cast device witout session."))};
g.h.sr=g.Ia;g.h.V=function(){this.info("disposeInternal");g.Do(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.w),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;r7.wb.V.call(this)};
g.h.zK=function(a,b){if(!this.fa())if(b){var c=w5(b);if(g.Oa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Bj(c));switch(d){case "mdxSessionStatus":q7(this,c.screenId);break;default:p7(this,"Unknown youtube message: "+d)}}else p7(this,"Unable to parse message.")}else p7(this,"No data in message.")};
g.h.Mu=function(a,b,c,d){k7(this.D,this.i.label,a,this.i.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(p7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Bo((0,g.x)(this.Mu,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.Xz=function(){return this.g};
g.h.cM=function(a){this.fa()||a||(p7(this,"Cast session died."),this.Md())};g.Ta(s7,o7);g.h=s7.prototype;g.h.rr=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.Wh=function(a){this.u=a;this.B()};
g.h.stop=function(){this.g();this.g=g.Ia;g.Do(this.w);this.o?this.o.stop((0,g.x)(this.Md,this,null),(0,g.x)(this.Md,this,"Failed to stop DIAL device.")):this.Md()};
g.h.V=function(){this.g();this.g=g.Ia;g.Do(this.w);this.o&&this.o.removeUpdateListener(this.I);this.o=null;s7.wb.V.call(this)};
g.h.fM=function(a){this.fa()||a||(p7(this,"DIAL session died."),this.g(),this.g=g.Ia,this.Md())};
g.h.yp=function(a){this.G=b5();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,u7(this));a(b);t7(this)}else this.B=(0,g.x)(function(){g.Do(this.w);this.B=g.Ia;this.w=NaN;var c=new chrome.cast.DialLaunchResponse(!0,u7(this));a(c);t7(this)},this),this.w=g.Bo((0,g.x)(function(){this.B()},this),100)};
g.h.HC=function(a,b,c){k7(this.D,this.C.receiver.label,a,this.i.friendlyName,(0,g.x)(function(d){d&&d.token?(this.Zm(d),b(new chrome.cast.DialLaunchResponse(!1))):this.yp(b,c)},this),(0,g.x)(function(d){p7(this,"Failed to get DIAL screen: "+d);
this.yp(b,c)},this))};g.Ta(v7,o7);v7.prototype.stop=function(){this.Md()};
v7.prototype.rr=g.Ia;v7.prototype.Wh=function(){g.Do(this.g);this.g=NaN;var a=d5(this.D.Kd(),this.i.label);a?this.Zm(a):this.Md(Error("No such screen"))};
v7.prototype.V=function(){g.Do(this.g);this.g=NaN;v7.wb.V.call(this)};g.Ta(w7,g.O);g.h=w7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.B);this.C||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.jJ,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.Tx,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.vH,this);chrome.cast.initialize(c,(0,g.x)(function(){this.fa()||
(chrome.cast.addReceiverActionListener(this.o),gqa(),this.i.subscribe("onlineScreenChange",(0,g.x)(this.Wz,this)),this.l=B7(this),chrome.cast.setCustomReceivers(this.l,g.Ia,(0,g.x)(function(k){this.Gb("Failed to set initial custom receivers: "+g.Bj(k))},this)),this.N("yt-remote-cast2-availability-change",z7(this)),b(!0))},this),(0,g.x)(function(k){this.Gb("Failed to initialize API: "+g.Bj(k));
b(!1)},this))};
g.h.iL=function(a,b){y7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)y7("Unsetting old screen status: "+this.g.i.friendlyName),A7(this,null)}if(a&&b){if(!this.g){c=d5(this.i.Kd(),a);if(!c){y7("setConnectedScreenStatus: Unknown screen.");return}var d=x7(this,c);d||(y7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ia,(0,g.x)(function(e){this.Gb("Failed to set initial custom receivers: "+g.Bj(e))},this)));
y7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);A7(this,new v7(this.i,d),!0)}this.g.sr(b)}else y7("setConnectedScreenStatus: no screen.")};
g.h.jL=function(a){this.fa()?this.Gb("Setting connection data on disposed cast v2"):this.g?this.g.Wh(a):this.Gb("Setting connection data without a session")};
g.h.eM=function(){this.fa()?this.Gb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),A7(this,null)):y7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.Tx,this),(0,g.x)(this.GJ,this))};
g.h.V=function(){this.i.unsubscribe("onlineScreenChange",(0,g.x)(this.Wz,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.eb(g.w("yt.mdx.remote.debug.handlers_")||[],O6);g.Ai(this.g);w7.wb.V.call(this)};
g.h.Gb=function(a){S6("Controller",a)};
g.h.Ux=function(a,b){this.g==a&&(b||A7(this,null),this.N("yt-remote-cast2-session-change",b))};
g.h.fJ=function(a,b){if(!this.fa())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),y7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)y7("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{y7("onReceiverAction_: Casting to active receiver.");this.g.l&&this.N("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:A7(this,
new v7(this.i,a));break;case chrome.cast.ReceiverType.DIAL:A7(this,new s7(this.i,a,this.w));break;case chrome.cast.ReceiverType.CAST:A7(this,new r7(this.i,a));break;default:this.Gb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Gb("Stopping receiver w/o session: "+a.friendlyName)}else this.Gb("onReceiverAction_ called without receiver.")};
g.h.vH=function(a){if(this.fa())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Gb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Gb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return y7("Reselecting dial screen."),
this.N("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Gb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);A7(this,new s7(this.i,b,this.w))}b=this.g;b.C=a;return b.C.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.HC,b,(b.C.extraData||{}).screenId||null)):new Promise((0,g.x)(b.yp,b))};
g.h.Tx=function(a){if(!this.fa()){y7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)y7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),A7(this,new r7(this.i,b),!0);else{this.Gb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=d5(this.i.Kd(),c.label);d&&X4(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(y7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ai(this.g),this.g=new r7(this.i,b),this.g.subscribe("sessionScreen",(0,g.x)(this.Ux,this,this.g)),this.g.Wh(null));this.g.rr(a)}}};
g.h.dM=function(){return this.g?this.g.Xz():null};
g.h.GJ=function(a){this.fa()||(this.Gb("Failed to estabilish a session: "+g.Bj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&A7(this,null))};
g.h.jJ=function(a){y7("Receiver availability updated: "+a);if(!this.fa()){var b=z7(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;z7(this)!=b&&this.N("yt-remote-cast2-availability-change",z7(this))}};
g.h.Wz=function(){this.fa()||(this.l=B7(this),y7("Updating custom receivers: "+g.Bj(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ia,(0,g.x)(function(){this.Gb("Failed to set custom receivers.")},this)),this.N("yt-remote-cast2-availability-change",z7(this)))};
w7.prototype.setLaunchParams=w7.prototype.jL;w7.prototype.setConnectedScreenStatus=w7.prototype.iL;w7.prototype.stopSession=w7.prototype.eM;w7.prototype.getCastSession=w7.prototype.dM;w7.prototype.requestSession=w7.prototype.requestSession;w7.prototype.init=w7.prototype.init;w7.prototype.dispose=w7.prototype.dispose;var K7=[];S7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";T7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.xe=a.hasPrevious,this.hasNext=a.hasNext,this.B=a.playerTime,this.w=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.C=a.duration,this.D=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
S7.prototype.isAdPlaying=function(){return 1081==this.playerState};
S7.prototype.getDuration=function(){return this.u?this.C+U7(this):this.C};
S7.prototype.clone=function(){return new S7(Y7(this))};g.r(a8,g.O);g.h=a8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ia,i8(this,"play")):g8(this,"play"),f8(this,1,W7(b8(this))),this.N("remotePlayerChange")):d8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ia,i8(this,"pause")):g8(this,"pause"),f8(this,2,W7(b8(this))),this.N("remotePlayerChange")):d8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=b8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ia,i8(this,"seekTo",{newTime:a}))}else g8(this,"seekTo",{newTime:a});f8(this,3,a);this.N("remotePlayerChange")}else d8(this,g.Ra(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ia,i8(this,"stopVideo")):g8(this,"stopVideo");var a=b8(this);a.index=-1;a.videoId="";T7(a);e8(this,a);this.N("remotePlayerChange")}else d8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=b8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.x)(function(){S6("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Gb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.x)(function(){S6("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Gb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);g8(this,"setVolume",e)}c.muted=b;c.volume=a;e8(this,c)}else d8(this,g.Ra(this.setVolume,a,b))};
g.h.Vy=function(a,b){if(1==this.g){var c=b8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Bj(b.style),g.ec(d,c.g));g8(this,"setSubtitlesTrack",d);e8(this,c)}else d8(this,g.Ra(this.Vy,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();g8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=b8(this);d.audioTrackId=c;e8(this,d)}else d8(this,g.Ra(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=b8(this);c=c||0;var m={videoId:a,currentIndex:c};X7(l,a,c);g.Ca(b)&&(V7(l,b),m.currentTime=b);g.Ca(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Bj(k));g8(this,"setPlaylist",m);d||e8(this,l)};
g.h.Sz=function(a,b){if(1==this.g){if(a&&b){var c=b8(this);X7(c,a,b);e8(this,c)}g8(this,"previous")}else d8(this,g.Ra(this.Sz,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=b8(this);X7(c,a,b);e8(this,c)}g8(this,"next")}else d8(this,g.Ra(this.nextVideo,a,b))};
g.h.Wt=function(){1==this.g?g8(this,"dismissAutoplay"):d8(this,this.Wt)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.N("proxyStateChange",a,this.g)}g.O.prototype.dispose.call(this)};
g.h.V=function(){c8(this);this.o=null;this.u.clear();$7(this,null);g.O.prototype.V.call(this)};
g.h.Wr=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.N("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,g.bb(b.g)&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.cJ=function(a,b){this.N(a,b)};
g.h.cH=function(a){if(!a)this.Xj(null),$7(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=b8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)S6("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,e8(this,b)}};
g.h.Xj=function(a){S6("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.C);if(this.i=a)this.i.addUpdateListener(this.C),h8(this),this.N("remotePlayerChange")};
g.h.bH=function(a){a?(h8(this),this.N("remotePlayerChange")):this.Xj(null)};
g.h.oH=function(){var a=O7();a&&$7(this,a)};
g.h.Gb=function(a){S6("CP",a)};g.r(j8,g.O);g.h=j8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ca(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ca(k)&&(l.currentIndex=k);c&&(this.Oa.listId=c);this.Oa.videoId=d;this.Oa.index=k||0;this.Oa.state=3;V7(this.Oa,m);this.o="UNSUPPORTED";k8("Connecting with setPlaylist and params: "+g.Bj(l));this.g.connect({method:"setPlaylist",
params:g.Bj(l)},a,j5())}else k8("Connecting without params"),this.g.connect({},a,j5());wqa(this)};
g.h.dispose=function(){this.fa()||(this.N("beforeDispose"),l8(this,3));g.O.prototype.dispose.call(this)};
g.h.V=function(){m8(this);o8(this);n8(this);g.Do(this.B);this.B=NaN;g.Do(this.C);this.C=NaN;this.l=null;g.Zq(this.R);this.R.length=0;this.g.dispose();g.O.prototype.V.call(this);this.o=this.w=this.i=this.Oa=this.g=null};
g.h.YB=function(){this.Ah(2)};
g.h.gH=function(){k8("Channel opened");this.I&&(this.I=!1,n8(this),this.G=g.Bo((0,g.x)(function(){k8("Timing out waiting for a screen.");this.Ah(1)},this),15E3));
Vpa(eqa(this.g),this.M)};
g.h.dH=function(){k8("Channel closed");isNaN(this.u)?m5(!0):m5();this.dispose()};
g.h.eH=function(a){m5();isNaN(this.ij())?(k8("Channel error: "+a+" without reconnection"),this.dispose()):(this.I=!0,k8("Channel error: "+a+" with reconnection in "+this.ij()+" ms"),l8(this,2))};
g.h.fH=function(a){a.params?k8("Received: action="+a.action+", params="+g.Bj(a.params)):k8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=w5(a.params.devices);this.i=(0,g.ee)(a,function(c){return new V4(c)});
a=!!g.Ya(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
r8(this,a);break;case "loungeScreenDisconnected":g.fb(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
r8(this,!1);break;case "remoteConnected":var b=new V4(w5(a.params.device));g.Ya(this.i,function(c){return b?c.id==b.id:!1})||Ipa(this.i,b);
break;case "remoteDisconnected":b=new V4(w5(a.params.device));g.fb(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":s8(this,a);break;case "nowPlaying":zqa(this,a);break;case "onStateChange":t8(this,a);break;case "onAdStateChange":Aqa(this,a);break;case "onVolumeChanged":Bqa(this,a);break;case "onSubtitlesTrackChanged":yqa(this,a);break;case "nowAutoplaying":Cqa(this,a);break;case "autoplayDismissed":this.N("autoplayDismissed");break;case "autoplayUpNext":this.w=a.params.videoId||null;this.N("autoplayUpNext",this.w);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.N("autoplayModeChange",this.o);"DISABLED"==this.o&&this.N("autoplayDismissed");break;case "onHasPreviousNextChanged":Dqa(this,a);break;case "requestAssistedSignIn":this.N("assistedSignInRequested",a.params.authCode);break;default:k8("Unrecognized action: "+a.action)}};
g.h.XK=function(){if(this.l){var a=this.l;this.l=null;this.Oa.videoId!=a&&p8(this,"getNowPlaying")}};
g.h.OB=function(){var a=3;this.fa()||(a=0,isNaN(this.ij())?K6(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
g.h.Ah=function(a){k8("Disconnecting with "+a);m8(this);this.N("beforeDisconnect",a);1==a&&m5();J6(this.g,a);this.dispose()};
g.h.NB=function(){var a=this.Oa;this.l&&(a=this.Oa.clone(),X7(a,this.l,a.index));return Y7(a)};
g.h.kL=function(a){var b=new S7(a);b.videoId&&b.videoId!=this.Oa.videoId&&(this.l=b.videoId,g.Do(this.B),this.B=g.Bo((0,g.x)(this.XK,this),5E3));var c=[];this.Oa.listId==b.listId&&this.Oa.videoId==b.videoId&&this.Oa.index==b.index||c.push("remoteQueueChange");this.Oa.playerState==b.playerState&&this.Oa.volume==b.volume&&this.Oa.muted==b.muted&&W7(this.Oa)==W7(b)&&g.Bj(this.Oa.g)==g.Bj(b.g)||c.push("remotePlayerChange");this.Oa.reset(a);(0,g.z)(c,function(d){this.N(d)},this)};
g.h.Ku=function(){var a=this.g.w.id,b=g.Ya(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.ij=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.A)():NaN};
g.h.HB=function(){return this.o||"UNSUPPORTED"};
g.h.IB=function(){return this.w||""};
g.h.WL=function(){if(!isNaN(this.ij())){var a=this.g.i;g.bn(a.g);a.start()}};
g.h.fL=function(a,b){p8(this,a,b);q8(this)};
j8.prototype.subscribe=j8.prototype.subscribe;j8.prototype.unsubscribeByKey=j8.prototype.yf;j8.prototype.getProxyState=j8.prototype.OB;j8.prototype.disconnect=j8.prototype.Ah;j8.prototype.getPlayerContextData=j8.prototype.NB;j8.prototype.setPlayerContextData=j8.prototype.kL;j8.prototype.getOtherConnectedRemoteId=j8.prototype.Ku;j8.prototype.getReconnectTimeout=j8.prototype.ij;j8.prototype.getAutoplayMode=j8.prototype.HB;j8.prototype.getAutoplayVideoId=j8.prototype.IB;j8.prototype.reconnect=j8.prototype.WL;
j8.prototype.sendMessage=j8.prototype.fL;g.r(u8,W6);g.h=u8.prototype;g.h.Kd=function(a){return this.Rc.$_gs(a)};
g.h.contains=function(a){return!!this.Rc.$_c(a)};
g.h.get=function(a){return this.Rc.$_g(a)};
g.h.start=function(){this.Rc.$_st()};
g.h.add=function(a,b,c){this.Rc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Rc.$_r(a,b,c)};
g.h.Gn=function(a,b,c,d){this.Rc.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.i.length;a<b;++a)this.Rc.$_ubk(this.i[a]);this.i.length=0;this.Rc=null;W6.prototype.V.call(this)};
g.h.aM=function(){this.N("screenChange")};
g.h.FI=function(){this.N("onlineScreenChange")};
i7.prototype.$_st=i7.prototype.start;i7.prototype.$_gspc=i7.prototype.bM;i7.prototype.$_gsppc=i7.prototype.Vz;i7.prototype.$_c=i7.prototype.contains;i7.prototype.$_g=i7.prototype.get;i7.prototype.$_a=i7.prototype.add;i7.prototype.$_un=i7.prototype.Gn;i7.prototype.$_r=i7.prototype.remove;i7.prototype.$_gs=i7.prototype.Kd;i7.prototype.$_gos=i7.prototype.Uz;i7.prototype.$_s=i7.prototype.subscribe;i7.prototype.$_ubk=i7.prototype.yf;var Q8=null,P8=!1,v8=null,w8=null,M8=null,A8=[];g.r(R8,g.F);g.h=R8.prototype;
g.h.V=function(){g.F.prototype.V.call(this);this.o.stop();this.w.stop();this.I.stop();this.M();this.g.unsubscribe("proxyStateChange",this.Qx,this);this.g.unsubscribe("remotePlayerChange",this.Zj,this);this.g.unsubscribe("remoteQueueChange",this.an,this);this.g.unsubscribe("autoplayUpNext",this.rx,this);this.g.unsubscribe("previousNextChange",this.Nx,this);this.g.unsubscribe("nowAutoplaying",this.Jx,this);this.g.unsubscribe("autoplayDismissed",this.qx,this);this.g=this.u=null};
g.h.mw=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(V8(this)){if(!b8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==b8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.G.Sl(c[0],c[1]);break;case "control_subtitles_set_track":W8(this,c[0]);break;case "control_set_audio_track":c=c[0],V8(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();X8(this,0==c?void 0:c);break;case "control_seek":X8(this,c[0]);break;case "control_subtitles_set_track":W8(this,c[0]);break;case "control_set_audio_track":c=c[0],V8(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.aH=function(a){this.I.UB(a)};
g.h.FL=function(a){this.mw("control_subtitles_set_track",g.Zb(a)?null:a)};
g.h.gz=function(){var a=this.i.getOption("captions","track");g.Zb(a)||W8(this,a)};
g.h.Cx=function(a){if(V8(this)){this.g.unsubscribe("remotePlayerChange",this.Zj,this);var b=Math.round(a.volume);a=!!a.muted;var c=b8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.R.start();this.g.subscribe("remotePlayerChange",this.Zj,this)}};
g.h.aI=function(){g.Zb(this.B)||Y8(this,this.B);this.C=!1};
g.h.Qx=function(a,b){this.w.stop();2==b&&this.fz()};
g.h.Zj=function(){if(V8(this)){this.o.stop();var a=b8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.D=1;break;case 1082:case 1083:this.u.D=0;break;default:this.u.D=-1}switch(a.playerState){case 1081:case 1:T8(this,new g.tt(8));this.ez();break;case 1085:case 3:T8(this,new g.tt(9));break;case 1083:case 0:T8(this,new g.tt(2));this.G.stop();S8(this,this.i.getVideoData().lengthSeconds);break;case 1084:T8(this,new g.tt(4));break;case 2:T8(this,new g.tt(4));S8(this,W7(a));
break;case -1:T8(this,new g.tt(64));break;case -1E3:T8(this,new g.tt(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=b8(this.g).g;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,Y8(this,a));a=b8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.R.isActive()||this.Hz()}else U8(this)};
g.h.Nx=function(){this.i.N("mdxpreviousnextchange")};
g.h.an=function(){V8(this)||U8(this)};
g.h.ZA=function(){this.g.Wt()};
g.h.rx=function(a){a&&!g.P(this.i.L().experiments,"disable_legacy_desktop_remote_queue")&&(a=g.zp("/watch_queue_ajax",{method:"GET",pd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.x)(this.hK,this)}))&&(this.M=(0,g.x)(a.abort,a))};
g.h.hK=function(a,b){var c=new g.DB(this.i.L(),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.N("mdxautoplayupnext",c)};
g.h.Jx=function(a){isNaN(a)||this.i.N("mdxnowautoplaying",a)};
g.h.qx=function(){this.i.N("mdxautoplaycanceled")};
g.h.xE=function(a,b){-1==b8(this.g).playerState?X8(this,a):b&&this.g.seekTo(a)};
g.h.Hz=function(){if(V8(this)){var a=b8(this.g);this.l.Sa(this.P);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.P=this.l.J(this.i,"onVolumeChange",this.Cx)}};
g.h.ez=function(){this.o.stop();if(!this.g.fa()){var a=b8(this.g);1==a.playerState&&T8(this,new g.tt(8));S8(this,W7(a));this.o.start()}};
g.h.fz=function(){this.w.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.w.start()};g.r($8,g.T);$8.prototype.o=function(){T4("mdx-privacy-popup-cancel");this.l.hide()};
$8.prototype.w=function(){T4("mdx-privacy-popup-confirm");this.l.hide()};g.r(b9,g.T);b9.prototype.u=function(a){a9(this,a.state)};g.r(c9,g.HN);c9.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.B=g.ub(a,this.w,this),g.JN(this,(0,g.ee)(a,this.w)),a=this.l.getOption("remote","currentReceiver"),this.de(this.w(a)),this.enable(!0)):this.enable(!1)};
c9.prototype.w=function(a){return a.key};
c9.prototype.le=function(a){return"cast-selector-receiver"==a?"Cast...":this.B[a].name};
c9.prototype.Jc=function(a){g.HN.prototype.Jc.call(this,a);this.l.setOption("remote","currentReceiver",this.B[a]);this.o.gb()};g.r(d9,g.QO);g.h=d9.prototype;
g.h.create=function(){Iqa(g.Jy(this.player.L()));this.o.push(g.Io("yt-remote-before-disconnect",this.XG,this));this.o.push(g.Io("yt-remote-connection-change",this.kJ,this));this.o.push(g.Io("yt-remote-receiver-availability-change",this.Ox,this));this.o.push(g.Io("yt-remote-auto-connect",this.iJ,this));this.o.push(g.Io("yt-remote-receiver-resumed",this.hJ,this));this.o.push(g.Io("mdx-privacy-popup-confirm",this.NK,this));this.o.push(g.Io("mdx-privacy-popup-cancel",this.MK,this));this.Ox()};
g.h.load=function(){this.player.cancelPlayback();g.QO.prototype.load.call(this);this.u=new R8(this,this.player,this.g);var a=(a=O8())?a.currentTime:0;var b=L8()?new a8(G8(),void 0):null;0==a&&b&&(a=W7(b8(b)));0!=a&&(this.R=a||0,this.player.N("progresssync",a,void 0));Z8(this,this.B,this.B);g.ZR(this.player.app,6)};
g.h.unload=function(){this.player.N("mdxautoplaycanceled");this.l=this.i;g.Bi(this.u,this.g);this.g=this.u=null;g.QO.prototype.unload.call(this);g.ZR(this.player.app,5);e9(this)};
g.h.V=function(){g.Jo(this.o);g.QO.prototype.V.call(this)};
g.h.Kj=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.u.mw.apply(this.u,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.D};
g.h.QB=function(){return this.loaded?this.u.suggestion:null};
g.h.xe=function(){return this.g?b8(this.g).xe:!1};
g.h.hasNext=function(){return this.g?b8(this.g).hasNext:!1};
g.h.getCurrentTime=function(){return this.R};
g.h.getProgressState=function(){var a=b8(this.g),b=this.player.getVideoData();return{allowSeeking:g.P(this.player.L().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.hc():!a.isAdPlaying()&&this.player.hc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+U7(a):a.l,isAtLiveHead:1>=(a.u?a.i+U7(a):a.i)-this.getCurrentTime(),loaded:a.D,seekableEnd:a.u?a.i+U7(a):a.i,seekableStart:0<a.o?a.o+U7(a):
a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.lE=function(){this.g&&this.g.Sz()};
g.h.XG=function(a){1==a&&(this.M=this.g?b8(this.g):null)};
g.h.kJ=function(){var a=L8()?new a8(G8(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.M=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.Ai(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.M)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,W7(a)));this.player.N("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Ox=function(){this.G=[this.i].concat(Jqa());var a=H8()||this.i;f9(this,a);this.player.ha("onMdxReceiversChange")};
g.h.EK=function(a){!this.I&&g.bD(a,8)&&(this.player.pauseVideo(),e9(this))};
g.h.iJ=function(){var a=H8();f9(this,a)};
g.h.hJ=function(){this.l=H8()};
g.h.NK=function(){this.I=!0;e9(this);P8=!1;Q8&&J8(Q8,1);Q8=null};
g.h.MK=function(){this.I=!1;e9(this);f9(this,this.i);this.l=this.i;P8=!1;Q8=null;this.player.playVideo()};
g.h.sc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?Q7():f9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&Q7(),!0):!1}};
g.h.mE=function(){g8(this.g,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Ne=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.dP.remote=d9;})(_yt_player);
