var xt1=".idealista.com",xtLogDom=".xiti.com/hit.xiti",xtpreview=!1,xtfirst=!1,xtnocookies=!1,xtcode="",xt46="1",xt50="1",xt48="",xt54=!1,xt58=!1,xtdocl=!1,xtud="undefined",xt2="0",xt3=3650,xttredir=500,xtkwv="xtmc",xtkwp="xtnp",xtadch=[],xt4=[];xt4.sec="20";xt4.rss="20";xt4.epr="20";xt4.erec="20";xt4.adi="20";xt4.adc="20";xt4.al="20";xt4.es="20";xt4.ad="20";
var xtoid=[],xtnop=!0,xtkey=!1,xt49=null,xt5=30,xw=window,xd=document,xtg=navigator,xtv=null!=xw.xtczv?"44007-"+xw.xtczv:"44007",xt1=xw.xtdmc?";domain\x3d"+xw.xtdmc:""!=xt1?";domain\x3d"+xw.xt1:"",xt6=null!=xw.xtnv?xw.xtnv:xd,xt7=null!=xw.xtsdi?xw.xtsdi:null!=xw.xtsd?xw.xtsd+xtLogDom:("https:"==xd.location.protocol?"https://logs3":"http://logi150")+xtLogDom,xt36=null!=xw.xtsts?xw.xtsts:0,xt37="";
if(xt54){var xturl="";try{xturl=xt6.location.href}catch(e){xturl=xw.location.href}xt37=(xt37=xtestr(xturl,/#.*/,1))?"\x26sta\x3d"+encodeURIComponent(xtclURL(xt37)):""}
var xt38=null!=xw.xtcustom?xtserial(xw.xtcustom):"",xt8=null!=xw.xtsite?xw.xtsite:0,xt9=null!=xw.xtn2?"\x26s2\x3d"+xw.xtn2:"",xt8b=(0==xt8?"":"s\x3d"+xt8)+(0==xt36?"":0==xt8?"sts\x3d"+xt36:"\x26sts\x3d"+xt36),xtp=null!=xw.xtpage?xw.xtpage:"",xt10=xw.xto_force?xw.xto_force.toLowerCase():null,xt11="redirect"==xt8?!0:!1,xtdi=xw.xtdi?"\x26di\x3d"+xw.xtdi:"",xt12=xw.xtidp?"\x26idpays\x3d"+xw.xtidp:"",xt13=xw.xtidprov?"\x26idprov\x3d"+xw.xtidprov:"",xtm=null!=xw.xtparam?xw.xtparam:"",xt46="undefined"!=
typeof xw.xtnopage&&"1"==xw.xtnopage?"0":xt46,xt50="undefined"!=typeof xw.xtergo&&"0"==xw.xtergo?"0":xt50,xtclzone="undefined"!=typeof xw.scriptOnClickZone&&"1"==xt50?xw.scriptOnClickZone:0,xt15=null!=xw.xt_orderid?xw.xt_orderid:"",xt17=null!=xw.xtidcart?xw.xtidcart:"",xt44=null!=xw.xtprod_load?"\x26pdtl\x3d"+xw.xtprod_load:"",xt47=""!=xw.xtcode?"\x26code\x3d"+xw.xtcode:"",xt60={i:[],u:[],d:[],l:[],e:[],p:[]};
xw.addEventListener?xw.addEventListener("unload",function(){},!1):xw.attachEvent&&xw.attachEvent("onunload",function(){});xd.addEventListener?(xd.addEventListener("keydown",function(){xtkey=!0},!1),xd.addEventListener("keyup",function(){xtkey=!1},!1)):xd.attachEvent&&(xd.attachEvent("onkeydown",function(){xtkey=!0}),xd.attachEvent("onkeyup",function(){xtkey=!1}));
var xt18=xw.roimt&&0>xtm.indexOf("\x26roimt",0)?"\x26roimt\x3d"+xw.roimt:"",xtmc=0>xtm.indexOf("\x26mc\x3d",0)?xw.xtmc?"\x26mc\x3d"+xw.xtmc:xtf3(xtkwv)?"\x26mc\x3d"+xtf3(xtkwv):xtf3("xtmc")?"\x26mc\x3d"+xtf3("xtmc"):"":"",xtcr=xtf3("xtcr")?"\x26mcrg\x3d"+xtf3("xtcr"):"",xtac=xw.xtac&&0>xtm.indexOf("\x26ac\x3d",0)?"\x26ac\x3d"+xw.xtac:"",xtat=xw.xtat&&0>xtm.indexOf("\x26at\x3d",0)?"\x26at\x3d"+xw.xtat:"",xtan=xw.xtan&&0>xtm.indexOf("\x26an\x3d",0)?"\x26an\x3d"+xw.xtan:"",xtnp=0>xtm.indexOf("\x26np\x3d",
0)?xw.xtnp?"\x26np\x3d"+xw.xtnp:xtf3(xtkwp)?"\x26np\x3d"+xtf3(xtkwp):xtf3("xtnp")?"\x26np\x3d"+xtf3("xtnp"):"":"",xt19=null!=xw.xtprm&&0>xtm.indexOf("\x26x",0)?xw.xtprm:"",xtm=xtm+(xt18+xtmc+xtcr+xtac+(""!=xtan?xtan:xtat)+xtnp+xt19+xt37),xt20="";try{xt20=top.document.referrer}catch(e$$1){try{xt20=xt6.referrer}catch(e$$2){}}var xts=screen,xt21=new Date,xt22=xt21.getTime()/36E5;
function xtserial(a){var b=typeof a;if("object"!=b||null===a)return"string"==b&&(a=encodeURIComponent('"'+a+'"')),String(a);var d,c,f=[],g=a&&a.constructor==Array;for(d in a)c=a[d],b=typeof c,"string"==b?c=encodeURIComponent('"'+c.replace(/[^\\]"/g,'\\"')+'"'):"object"==b&&null!==c&&(c=xtserial(c)),f.push((g?"":encodeURIComponent('"'+d+'":'))+String(c));return(g?"[":"{")+String(f)+(g?"]":"}")}function xtclURL(a){return a.replace(/%3C/g,"\x3c").replace(/%3E/g,"\x3e").replace(/[<>]/g,"")}
function xtf1(a,b){if(xtnocookies)return null;b=null!=b&&b!=xtud?b:"0";var d=RegExp("(?:^| )"+a+"\x3d([^;]+)").exec(xd.cookie)||null;d&&(d=xtclURL(d[1]),"1"!=b&&(d=unescape(d)));return d}function xt_addchain(a,b){xtvarch=b?b:"abmv";itemp=xtadch[xtvarch]?xtadch[xtvarch]:0;itemp++;xtm+="\x26"+xtvarch+""+itemp+"\x3d"+a;xtadch[xtvarch]=itemp}"function"==typeof xt_adch&&xt_adch();
function wck(a,b,d,c,f){b=0==f?b:escape(b);xtnocookies||(xd.cookie=a+"\x3d"+b+";expires\x3d"+d.toGMTString()+";path\x3d/"+c)}
function xtf3(a,b,d){try{var c=xt6.location.href}catch(f){c=xw.location.href}b=null==b||b==xtud?xtclURL(c.toLowerCase().replace(/%3d/g,"\x3d")):b;if(0<b.indexOf(a+"\x3d")){b=b.substr(1);a=b.substr(b.indexOf(a+"\x3d"));if(2!=d){if(1!=d)try{a=decodeURIComponent(a)}catch(g){a=unescape(a)}if(b=a.match(/(\[[^\]]*\])/g))for(var c="",k=0,h=b.length;k<h;k++)c=b[k].substring(1,b[k].length-1),a=a.replace(c,encodeURIComponent(c))}b=a.indexOf("#");c=a.search(/&.[^&]+=/gi);c=-1==c?-1==b?a.length:b:0<b&&b<c?b:
c;return 1==d?decodeURIComponent(a.substring(a.indexOf("\x3d")+1,c)):2==d?a.substring(a.indexOf("\x3d")+1,c):a.substring(a.indexOf("\x3d")+1,c).replace("\x26","%26")}return null}function xt_mvt(a,b,d,c,f){if(c)for(var g=1;g<c.length+1;g++)d+="\x26"+(f?f:"abmv")+g+"\x3d"+c[g-1];xtf4("","\x26p\x3d"+a+"\x26s2\x3d"+b+"\x26abmvc\x3d"+d+"\x26type\x3dmvt")}function xt_med(a,b,d,c,f,g,k,h){}
if(xtfirst=-1!=xtg.userAgent.indexOf("Safari")&&0>xtg.userAgent.indexOf("Chrome")||-1!=xtg.userAgent.indexOf("iPhone")||-1!=xtg.userAgent.indexOf("iPod")||-1!=xtg.userAgent.indexOf("iPad")||xtfirst||xw.xtidc||xtnocookies){var xt40=xw.xtidc?xw.xtidc:xtf1("xtidc");if(null==xt40){var xt40=Math.floor(999999*Math.random()),xtane=xt21.getYear();100>xtane&&(xtane+=2E3);100<xtane&&2E3>xtane&&(xtane+=1900);var xt41=f_nb(xtane)+""+f_nb(xt21.getMonth())+""+f_nb(xt21.getDate())+""+f_nb(xt21.getHours())+""+f_nb(xt21.getMinutes())+
""+f_nb(xt21.getSeconds()),xt40=xt41+""+xt40}var xtdrc=new Date;xtdrc.setTime(xtdrc.getTime()+31536E7);wck("xtidc",xt40,xtdrc,xt1,1);xt42=xtf1("xtidc");xt40+=xw.xtidc||null!=xt42&&xt42==xt40?"":"-NO"}function xt_ad(a,b,d){xtf4("AT","\x26atc\x3d"+a+"\x26type\x3dAT\x26patc\x3d"+xtp+"\x26s2atc\x3d"+xw.xtn2,b,d)}function xt_adi(a,b,d){xtf4("AT","\x26ati\x3d"+a+"\x26type\x3dAT",b,d)}
function xt_adc(a,b,d,c){xtf4("AT","\x26atc\x3d"+b+"\x26type\x3dAT\x26patc\x3d"+xtp+"\x26s2atc\x3d"+xw.xtn2);return AT_click.do_navig(a,d,c?"_blank":null,!0)}function xt_click(a,b,d,c,f,g,k){xt_ajout="F"!=b||null!=f&&f!=xtud?"\x26clic\x3d"+f:"";xtf4(b,"\x26s2\x3d"+d+"\x26p\x3d"+c+xt_ajout);return AT_click.do_navig(a,g,k?"_blank":null,!0)}
function xt_form(a,b,d,c,f,g){xt_ajout="F"!=b||null!=f&&f!=xtud?"\x26clic\x3d"+f:"";xtf4(b,"\x26s2\x3d"+d+"\x26p\x3d"+c+xt_ajout);return AT_click.do_submit(a,!0,g)}
var AT_click={id:0,objs:[],elem:function(a,b,d,c,f,g,k){var h={};h.urlDest=f;h.type=a;h.n2=b;h.label=d;h.typeClick=c;h.target=g;h.submit=!1===f?!1:!0;h.redir=null==k?!0:k;return h},addListener:function(a,b,d){window.addEventListener?a.addEventListener(b,d,!1):window.attachEvent&&a.attachEvent("on"+b,d)},tag:function(a,b,d,c,f,g,k,h){if(a&&"function"==typeof a.setAttribute)this.addElem(a,b,d,c,f,g,k,h);else if("object"==typeof a)for(var l in a)"function"==typeof a[l].setAttribute&&this.addElem(a[l],
b,d,c,f,g,k,h)},addElem:function(a,b,d,c,f,g,k,h){this.id++;a.setAttribute("data-xtclickid",this.id);this.objs[this.id]=this.elem(b,d,c,f,g,k,h);"FORM"!=a.nodeName?this.addListener(a,"click",this.on_click_submit):this.addListener(a,"submit",this.on_click_submit)},on_click_submit:function(a){try{var b=a.target||a.srcElement,d=b.getAttribute("data-xtclickid"),c={},f="",g=a.defaultPrevented,k=AT_click;if(!d)for(var h=b.parentNode;h;){if(h.getAttribute("data-xtclickid")){d=h.getAttribute("data-xtclickid");
break}h=h.parentNode}d&&(c=k.objs[d],"AT"!=c.type?f+="\x26p\x3d"+c.label+("C"==c.type?"\x26clic\x3d"+c.typeClick:""):"AT"==c.type&&(f+="\x26type\x3dAT\x26atc\x3d"+c.label),xtf4(c.type,"\x26s2\x3d"+c.n2+f),!g&&c.redir&&(a.preventDefault(),"FORM"!=b.nodeName?k.do_navig(b,c.urlDest,c.target):k.do_submit(b,null,c.submit)))}catch(l){}},do_navig:function(a,b,d,c){var f=null;if("A"!=a.nodeName)for(var g=a.parentNode;g;){if("A"==g.nodeName){f=g;break}g=g.parentNode}else f=a;if(f){if(f.target=d||a.target||
"_self",f.href=b||a.href||f.href,!c||c&&!xtkey)if(0>f.href.indexOf("mailto:"))if("_self"==f.target.toLowerCase()){if(setTimeout('self.location.href\x3d"'+f.href+'"',xw.xttredir),c)return!1}else if("_top"==f.target.toLowerCase()){if(setTimeout('top.location.href\x3d"'+f.href+'"',xw.xttredir),c)return!1}else if("_parent"==f.target.toLowerCase()){if(setTimeout('parent.location.href\x3d"'+f.href+'"',xw.xttredir),c)return!1}else{if("_blank"==f.target.toLowerCase()&&(setTimeout('(xw.open("'+f.href+'","_blank")).focus();',
1),c))return!1}else if(setTimeout('AT_click.mail_to("'+f.href+'");',xw.xttredir),c)return!1}else if(b||a.href)if(b=b?b:a.href,0>b.indexOf("mailto:"))if("_blank"==d)setTimeout('(xw.open("'+b+'","_blank")).focus();',1);else{if(setTimeout('self.location.href\x3d"'+b+'"',xw.xttredir),c)return!1}else if(setTimeout('AT_click.mail_to("'+b+'");',xw.xttredir),c)return!1;if(c)return xtkey=!1,!0},do_submit:function(a,b,d){if(d&&(setTimeout(function(){a.submit()},500),b&&d))return!1},mail_to:function(a){window.location=
a}};
function xt_rm(a,b,d,c,f,g,k,h,l,m,p,n,q,r){xtf4(a,"\x26p\x3d"+d+"\x26s2\x3d"+b+"\x26type\x3d"+a+"\x26a\x3d"+c+"\x26m5\x3d"+p+"\x26m6\x3d"+n+(null!=f&&"0"!=f?"\x26"+f:"")+(null!=k&&"pause"!=c&&"stop"!=c?"\x26m1\x3d"+k+"\x26"+h+"\x26m3\x3d"+l+"\x26m4\x3d"+m+"\x26m7\x3d"+q+"\x26m8\x3d"+r+"\x26prich\x3d"+xtp+"\x26s2rich\x3d"+xw.xtn2:"")+(null!=g&&"0"!=g&&null!=k?"\x26rfsh\x3d"+g:""));f=new Date;null==g||"0"==g||"play"!=c&&"play\x26buf\x3d1"!=c&&"refresh"!=c?"pause"!=c&&"stop"!=c||null==xw.xtoid||(xw.clearTimeout(xtoid[a]),
"stop"==c?xt60.i[a]=0:xt60.p[a]=f.getTime()):(xt60.p[a]&&18E5<f.getTime()-xt60.p[a]&&(xt60.d[a]=0),"play"!=c&&"play\x26buf\x3d1"!=c||xt60.d[a]?"refresh"==c&&("live"==n||!xt60.l[a]||300<xt60.l[a]&&2>100*xt60.i[a]/xt60.l[a])&&(c=xt60.p[a]?xt60.e[a]:f.getTime()/1E3-xt60.d[a],5>100*xt60.u[a]/(c+30)&&(xt60.u[a]=5*((c+30)/100)),xt60.p[a]&&(xt60.p[a]=!1,xt60.d[a]=f.getTime()/1E3-xt60.e[a]),xt60.e[a]=c):(xt60.d[a]=f.getTime()/1E3,xt60.l[a]=parseInt(k),c=Math.floor(g),c=1500<c?1500:5>c?5:c,xt60.i[a]=c,xt60.u[a]=
c,xt60.p[a]=!1),xtoid[a]=xw.setTimeout("xt_rm('"+a+"','"+b+"','"+d+"','refresh','0','"+g+"',null,'"+h+"','"+l+"','"+m+"','"+p+"','"+n+"')",1E3*xt60.u[a]))}
function xtf4(a,b,d,c){0!=xtclzone&&3!=xtclzone&&"C"==a||"P"==a||(xtnop&&"0"==xt46&&"F"==a?(Xt_param=Xt_param.replace("\x26p\x3d"+xtf3("p",Xt_param,2),""),Xt_param=Xt_param.replace("\x26s2\x3d"+xtf3("s2",Xt_param),""),AT_hit.isPreviewOrPrerendering()||AT_hit.sendTag(a,null,null,b),xtnop=!1):AT_hit.sendTag(a,b));null!=d&&d!=xtud&&"M"!=a&&(""==c||null==c?setTimeout('window.location.href\x3d"'+d+'"',xw.xttredir):(xfen=window.open(d,"xfen",""),xfen.focus()))}
function f_nb(a){a-=100*Math.floor(a/100);return 10>a?"0"+a:a}var xtidpg=f_nb(xt21.getHours())+""+f_nb(xt21.getMinutes())+""+f_nb(xt21.getSeconds())+""+xt_rd(7),xt23=0,xt16="",xt43=0;function xt_addProduct(a,b,d,c,f,g){xt23++;xt16+="\x26pdt"+xt23+"\x3d";xt16+=a?a+"::":"";xt16+=b?b:"";xt16+=d?"\x26qte"+xt23+"\x3d"+d:"";xt16+=c?"\x26mt"+xt23+"\x3d"+c:"";xt16+=f?"\x26dsc"+xt23+"\x3d"+f:"";xt16+=g?"\x26pcode"+xt23+"\x3d"+g:""}function xt_rd(a){return Math.floor(Math.random()*Math.pow(10,a))}
function xt_addProduct_v2(a,b,d,c,f,g,k,h,l){xt23++;xt16+="\x26pdt"+xt23+"\x3d";xt16+=a?a+"::":"";xt16+=b?b:"";xt16+=d?"\x26qte"+xt23+"\x3d"+d:"";xt16+=c?"\x26mt"+xt23+"\x3d"+c:"";xt16+=f?"\x26mtht"+xt23+"\x3d"+f:"";xt16+=g?"\x26dsc"+xt23+"\x3d"+g:"";xt16+=k?"\x26dscht"+xt23+"\x3d"+k:"";xt16+=l?"\x26roimt"+xt23+"\x3d"+l:"";xt16+=h?"\x26pcode"+xt23+"\x3d"+h:""}function xt_addProduct_load(a,b,d){b&&(xt43++,xt44+=1==xt43?"\x26pdtl\x3d":"|",xt44+=a?a+"::":"",xt44+=b,xt44+=d?";"+d:"")}
"function"==typeof xt_cart?xt_cart():xt16="";function xtestr(a,b,d){var c=null;try{c=a.match(b)[d-1]}catch(f){c=null}return c}
var AT_hit={first:!0,referrer:("acc_dir"==xtf3("xtref")?"":null!=xtf3("xtref")?xtf3("xtref"):"acc_dir"==xtf1("xtref")?"":xtf1("xtref")||xt20.replace(/[<>]/g,"")||"").replace(/[<>]/g,"").substring(0,1600),parse:function(a,b,d,c){var f=[""];if(1600>=b.length)f[0]=b;else{a=AT_hit.first&&"F"==a?xtidpg:xtidpg.substring(0,6)+xt_rd(8);var g="",k="",h,l={};h=[];var m=0;0<=b.indexOf("\x26ref\x3d")&&(g=b.substring(b.indexOf("\x26ref\x3d")+1),b=b.replace(g,""));if(c)for(var p in c)0<=b.indexOf("\x26"+p+"\x3d")&&
1600<(k=xtf3(p,b,2)).length&&(b=b.replace("\x26"+p+"\x3d"+k,""),h=RegExp("["+c[p]+"]","gi"),l[p]=k.replace(/&/g,"%26").split(h));h=RegExp("["+d+"]","gi");h=b.split(h);for(var n in h)1600>=f[m].length+h[n].length+1?f[m]+=""!=h[n]?"\x26"+h[n]:"":(f.push(""),m++,f[m]=1600>h[n].length?f[m]+(""!=h[n]?"\x26"+h[n]:""):f[m]+("\x26mherr\x3d1\x26"+h[n].substring(0,1600)));for(var q in l)for(n="\x26"+q+"\x3d",b=!1,d=l[q].length,p=0;p<d;p++)1600>=f[m].length+l[q][p].length+1?(b||(f[m]+=n,b=!0),f[m]+=""!=l[q][p]?
l[q][p]+c[q]:""):(f.push(n),m++,f[m]=1600>l[q][p].length?f[m]+(""!=l[q][p]?l[q][p]+c[q]:""):f[m]+("mherr\x3d1"+c[q]));g&&(1600>=f[m].length+g.length||(f.push(""),m++),f[m]+="\x26"+g);for(c=0;c<f.length;c++)f[c]="\x26mh\x3d"+(c+1)+"-"+f.length+"-"+a+f[c]}return f},sendTag:function(a,b,d,c){var f=[];d=d||Xt_id+xt8b;d+=xw.xtfirst?"\x26idclient\x3d"+xt40:"";a=a||"F";b=b||Xt_param;b+=(c?c:"")+"\x26vtag\x3d"+xtv+AT_hit.localHour()+AT_hit.resolution();AT_hit.first&&"F"==a&&(d+=""!=xt15||""!=xt17?"\x26cmd\x3d"+
xt15+"\x26idcart\x3d"+xt17:"",b+=xt38?"\x26stc\x3d"+xt38:"",b+="\x26ref\x3d"+AT_hit.referrer.replace(/&/g,"$"));f=AT_hit.parse(a,b,"\x26",{ati:",",atc:",",pdtl:"|",stc:",",dz:"|"});for(b=0;b<f.length;b++)AT_hit.loadImage(d+f[b]);AT_hit.first&&"F"==a&&"undefined"!=typeof xtscript&&AT_hit.loadFile("script",xtscript,!0,"text/javascript");"F"==a&&(AT_hit.first=!1)},loadImage:function(a){},loadFile:function(a,b,d,c,f){a=document.createElement(a);a.type=c;a.async=d;a.src=b;(f||document.getElementsByTagName("head")[0]||
document.getElementsByTagName("body")[0]||document.getElementsByTagName("script")[0].parentNode).insertBefore(a,null)},localHour:function(a){a=a?a:new Date;return"\x26hl\x3d"+a.getHours()+"x"+a.getMinutes()+"x"+a.getSeconds()},resolution:function(){if(4<=parseFloat(xtg.appVersion))try{return"\x26r\x3d"+xts.width+"x"+xts.height+"x"+xts.pixelDepth+"x"+xts.colorDepth}catch(a){}return""},prerenderDisplaying:function(){AT_hit.first&&(AT_hit.sendTag("F"),""!=xt44&&AT_hit.sendTag("PDT",xt44,null,"\x26type\x3dPDT\x26p\x3d"+
xtp+(xw.xt_pageID?"\x26pid\x3d"+xw.xt_pageID+"\x26pchap\x3d"+(xw.xt_chap||"")+"\x26pidt\x3d"+(xw.xt_pageDate||""):"")))},isPreviewOrPrerendering:function(){return window.navigator&&"preview"===window.navigator.loadPurpose&&-1!=xtg.userAgent.indexOf("Safari")&&0>xtg.userAgent.indexOf("Chrome")?(xtpreview&&(AT_hit.sendTag("F",null,null,"\x26pvw\x3d1"),""!=xt44&&AT_hit.sendTag("PDT",xt44,null,"\x26type\x3dPDT\x26p\x3d"+xtp+(xw.xt_pageID?"\x26pid\x3d"+xw.xt_pageID+"\x26pchap\x3d"+(xw.xt_chap||"")+"\x26pidt\x3d"+
(xw.xt_pageDate||""):""))),!0):"prerender"==xd.webkitVisibilityState?(xd.addEventListener("webkitvisibilitychange",AT_hit.prerenderDisplaying,!1),!0):!1}};function xt_ParseUrl(a,b,d,c){AT_hit.sendTag(d?"F":"old",b)}function xt_ParseUrl3(a,b,d,c,f,g,k){AT_hit.sendTag("\x26ati\x3d"==f?"AT":"PDT",b,null,"\x26type\x3d"+("\x26ati\x3d"==f?"AT":"PDT"))}
if(0!=xt8||0!=xt36||xt11){if(""!=xt48){var xtvid=xtf1("xtvid");xtvid||(xt49=xtvid=xt21.getTime()+""+xt_rd(6));var xtexp=new Date;xtexp.setMinutes(xtexp.getMinutes()+30);wck("xtvid",xtvid,xtexp,"",1)}var xtpm="xtor"+xt8,xtpmd="xtdate"+xt8,xtpmc="xtocl"+xt8,xtpan="xtan"+xt8,xtpat="xtat"+xt8,xtpant="xtant"+xt8,xt24=xtf3("xtor"),xtdtgo=xtf3("xtdt"),xt26=xtf3("xtan"),xt55=xtf3("xtat"),xt27=xtf3("an",xtm),xt56=xtf3("at",xtm),xt28=xtf3("ac",xtm),cookie_xtpmc=xtf1(xtpmc),cookie_xtgo=xtf1("xtgo"),cookie_xtord=
xtf1("xtord"),cookie_xtvrn=xtf1("xtvrn"),xtocl=null!=cookie_xtpmc?cookie_xtpmc:"$",xtord="0"==cookie_xtgo?cookie_xtord:null,xtgord=null!=cookie_xtgo?cookie_xtgo:"0",xtvrn=null!=cookie_xtvrn?cookie_xtvrn:"$",xtgmt=xt21.getTime()/6E4,xtgo=null!=xtdtgo&&xtf3("xts")==xt8?30>xtgmt-xtdtgo&&0<=xtgmt-xtdtgo?"2":"1":xtgord,xtpgt="1"==xtgord?"\x26pgt\x3d"+cookie_xtord:"1"==xtgo&&null!=xt24?"\x26pgt\x3d"+xt24:"",xto=null!=xt10?xt10:null!=xt24&&"0"==xtgo?xt24:xt11?null:xtord,xto=0>xtocl.indexOf("$"+xto+"$")||
"$"==xtocl?xto:null,xtock="0"==xtgo?xto:"2"==xtgord?cookie_xtord:"2"==xtgo?xt24:null;if(null!=xtock){tmpxto=xtock.substring(0,xtock.indexOf("-"));var xtdrm=xt4[tmpxto]}else xtdrm="1";if(null==xtdrm||xtdrm==xtud)xtdrm=xt4.ad;null!=xt26||xt11||(xt26=xtf1("xtanrd"));null!=xt55||xt11||(xt55=xtf1("xtatrd"));var xtanc=xtf1(xtpan),xtattc=xtf1(xtpat),xtanct=xtf1(xtpant),xtxp=new Date,xt29=new Date,xt30=new Date;xt11?xtxp.setTime(xtxp.getTime()+1E3*xt5):xtxp.setTime(xtxp.getTime()+864E5*xtdrm);xt30.setTime(xt30.getTime()+
18E5);xt29.setTime(xt29.getTime()+864E5*xt3);var xt31=null!=xt26?xt26.indexOf("-"):0,xt57=null!=xt55?xt55.indexOf("-"):0,xtan2=null!=xt27?"":null!=xt26&&0<xt31?"\x26ac\x3d"+xt26.substring(0,xt31)+"\x26ant\x3d0\x26an\x3d"+xt26.substring(xt31+1,xt26.length):null!=xtanc?"\x26anc\x3d"+xtanc+"\x26anct\x3d"+xtanct:"",xtat2=null!=xt56?"":null!=xt55&&0<xt57?"\x26ac\x3d"+xt55.substring(0,xt57)+"\x26ant\x3d0\x26at\x3d"+xt55.substring(xt57+1,xt55.length):null!=xtattc?"\x26attc\x3d"+xtattc+"\x26anct\x3d"+xtanct:
"",xt32=0>xtvrn.indexOf("$"+xt8+"$")?"\x26vrn\x3d1":"",xt35=null!=xtf3("xtatc")&&null==xtf3("atc",xtm)?"\x26atc\x3d"+xtf3("xtatc"):"";""!=xt32&&wck("xtvrn",141>xtvrn.length?xtvrn+xt8+"$":xtvrn.substring(0,141),xt29,xt1,0);xt32+=null==xto?"":"\x26xto\x3d"+xto;xt32+=(""!=xtan2?xtan2:xtat2)+xtpgt+xt35;null!=xt27?(wck(xtpan,xt28+"-"+xt27,xt29,xt1,1),wck(xtpant,"1",xt29,xt1,1)):null!=xt26&&"1"!=xtanct&&(wck(xtpan,xt26,xt29,xt1,1),wck(xtpant,"0",xt29,xt1,1));null!=xt56?(wck(xtpat,xt28+"-"+xt56,xt29,xt1,
1),wck(xtpant,"1",xt29,xt1,1)):null!=xt55&&"1"!=xtanct&&(wck(xtpat,xt55,xt29,xt1,1),wck(xtpant,"0",xt29,xt1,1));var xtor=xtf1(xtpm),xtor_duree=xtf1(xtpmd),xtor_duree=(/[a-zA-Z]/.test(xtor_duree)?(new Date(xtor_duree)).getTime()/36E5:parseFloat(xtf1(xtpmd)))||(new Date).getTime()/36E5,xtecart=0<=Math.floor(xt22-xtor_duree)?Math.floor(xt22-xtor_duree):0,xt32=xt32+(null==xtor?"":"\x26xtor\x3d"+xtor+"\x26roinbh\x3d"+xtecart);if(xt11)wck("xtgo",xtgo,xtxp,xt1,1),null!=xt24&&wck("xtord",xt24,xtxp,xt1,1),
null!=xt26&&wck("xtanrd",xt26,xtxp,xt1,1),null!=xt55&&wck("xtatrd",xt55,xtxp,xt1,1),wck("xtref",AT_hit.referrer?AT_hit.referrer.replace(/&/g,"$"):"acc_dir",xtxp,xt1,0),null!=xw.xtloc&&(xt6.location=xw.xtloc);else{null!=xtock&&(0>xtocl.indexOf("$"+escape(xtock)+"$")||"$"==xtocl)&&wck(xtpmc,xtocl+xtock+"$",xt30,xt1,1);var xtnav=xtg.appName+" "+xtg.appVersion,xtIE=xtnav.indexOf("MSIE");if(0<=xtIE)var xtvers=parseInt(xtnav.substr(xtIE+5)),xtIE=!0;else xtvers=parseFloat(xtg.appVersion),xtIE=!1;var xtnet=
0<=xtnav.indexOf("Netscape"),xtmac=0<=xtnav.indexOf("Mac"),xtOP=0<=xtg.userAgent.indexOf("Opera");if(xtIE&&5<=xtvers&&!xtmac&&!xtOP&&!xt11)try{xd.body.addBehavior("#default#clientCaps");var xtconn="\x26cn\x3d"+xd.body.connectionType,xtconn=xtconn+("\x26ul\x3d"+xd.body.UserLanguage);xd.body.addBehavior("#default#homePage");var xthome="",xthome=xd.body.isHomePage(location.href)?"\x26hm\x3d1":"\x26hm\x3d0",xtresr="\x26re\x3d"+xd.body.offsetWidth+"x"+xd.body.offsetHeight}catch(e$$18){}else xthome=xtconn=
"",xtresr=5<=xtvers?"\x26re\x3d"+xw.innerWidth+"x"+xw.innerHeight:"";var xtlang=xtnet&&4<=xtvers||xtOP?"\x26lng\x3d"+xtg.language:xtIE&&4<=xtvers&&!xtOP?"\x26lng\x3d"+xtg.userLanguage:"";wck("xtord","",xt21,xt1,1);null==xtock||null!=xtor&&"1"!=xt2||(wck(xtpm,xtock,xtxp,xt1,1),wck(xtpmd,xt21.getTime()/36E5,xtxp,xt1,1));var xt45=xtdocl?"\x26docl\x3d"+encodeURIComponent(xt6.location.href.replace(/&/g,"#ec#")):"",Xt_param=xt9+"\x26p\x3d"+xtp+AT_hit.localHour()+xtdi+xt12+xt13+xt32+xt45+xt47+xtm+xtconn+
xthome+xtlang+"\x26idp\x3d"+xtidpg,xtvalCZ=xtf1("xtvalCZ",1);if(null!=xtvalCZ){var Xt_param=Xt_param+xtvalCZ.replace("\x26c\x3d","\x26current\x3d").replace("\x26b\x3d","\x26before\x3d").replace("\x26a\x3d","\x26after\x3d"),xtdateo=new Date;xtdateo.setTime(xtdateo.getTime()-36E5);wck("xtvalCZ",xtvalCZ,xtdateo,xt1,1)}var Xt_id=xt7+"?",xtide=xtf1("xtide");if(null!=xtock)switch(tmpxto.toLowerCase()){case "erec":case "epr":case "es":var xtmpide=null;try{var xtide_t=xtock.match(/(\[[^\]]*\])|([^\-]+)|(-)/g),
xtide_c=0;for(elem in xtide_t)"-"==xtide_t[elem]&&xtide_c++,5==xtide_c&&"-"!=xtide_t[elem]&&(xtmpide=xtide_t[elem])}catch(e$$19){xtmpide=null}null!=xtmpide&&(xtide=xtmpide,wck("xtide",xtide,xt29,"",1))}var Xt_param=Xt_param+("\x26jv\x3d"+(xtg.javaEnabled()?"1":"0")+xtresr+xt16+(null!=xtide?"\x26ide\x3d"+xtide:"")),Xt_i=Xt_id+Xt_param+"\x26ref\x3d"+AT_hit.referrer.replace(/&/g,"$");xt49&&(Xt_param+="\x26lnk\x3d"+xt48+"\x26vid\x3d"+xt49);"0"==xt46||AT_hit.isPreviewOrPrerendering()||(AT_hit.sendTag("F"),
""!=xt44&&AT_hit.sendTag("PDT",xt44,null,"\x26type\x3dPDT\x26p\x3d"+xtp+(xw.xt_pageID?"\x26pid\x3d"+xw.xt_pageID+"\x26pchap\x3d"+(xw.xt_chap||"")+"\x26pidt\x3d"+(xw.xt_pageDate||""):"")))}}0<xtclzone&&"function"==typeof xtNodesload&&(xt58?xw.addEventListener?xw.addEventListener("load",xtNodesload,!1):xw.attachEvent&&xw.attachEvent("onload",xtNodesload):xtNodesload());xtkey=!1;
document.addEventListener?(document.addEventListener("keydown",function(){xtkey=!0},!1),document.addEventListener("keyup",function(){xtkey=!1},!1)):document.attachEvent&&(document.attachEvent("onkeydown",function(){xtkey=!0}),document.attachEvent("onkeyup",function(){xtkey=!1}));
function xt_conversion(a,b,d,c,f,g,k,h,l){var m=new Image,p=new Date,n=window.screen,q=window.navigator,r=null;d=(null!=window.xtsd?window.xtsd:"http://log")+".xiti.com/hit.xiti?s\x3d"+(null!=window.xtsite?window.xtsite:0)+"\x26s2\x3d"+d+"\x26p\x3d"+c+("F"==b?"":"M"==b?"\x26a\x3d"+f+"\x26m1\x3d"+g+"\x26m2\x3d"+k+"\x26m3\x3d"+h+"\x26m4\x3d"+l:"\x26clic\x3d"+f)+"\x26hl\x3d"+p.getHours()+"x"+p.getMinutes()+"x"+p.getSeconds();4<=parseFloat(q.appVersion)&&(d+="\x26r\x3d"+n.width+"x"+n.height+"x"+n.pixelDepth+
"x"+n.colorDepth);m.src=d;m.onload=function(){m.onload=null};if("A"!=a.nodeName)for(a=a.parentNode;a;){if("A"==a.nodeName){r=a;break}a=a.parentNode}else r=a;if(r){if(r.target=r.target||"_self",g&&"C"==b&&(r.href=g,r.target=k?"_blank":"_self"),!xtkey){if("_self"==r.target.toLowerCase())return setTimeout('self.location.href\x3d"'+r.href+'"',500),!1;if("_top"==r.target.toLowerCase())return setTimeout('top.location.href\x3d"'+r.href+'"',500),!1;if("_parent"==r.target.toLowerCase())return setTimeout('parent.location.href\x3d"'+
r.href+'"',500),!1}}else g&&"C"==b&&(k?setTimeout('(window.open("'+g+'","_blank")).focus();',500):setTimeout('self.location.href\x3d"'+g+'"',500));xtkey=!1;return!0}
var scriptOnClickZone=2,xtautoredir=!0,xtczv="32006",xtdtmp=0,xtdt2=new Date,xtel=new xtE(xtdt2.getTime()),xtn=navigator,un=void 0,nu=null,cZ="xtcz",oC="onclick",cL="xtclib",cT="xtcltype",dT="xtdztype",tR=!0,fA=!1,isI=/MSIE/.test(xtn.userAgent)?tR:fA,isOP=/Opera/.test(xtn.userAgent)?tR:fA,isS=/Safari/.test(xtn.userAgent)?tR:fA,isM=0<=xtn.appVersion.indexOf("Mac",0)?tR:fA,xtobj=[],xtcz=[],typcz=[],sizex=[],sizey=[],posx=[],posy=[],larg=0,haut=0,xt_valdz=nu,hit=fA,timecz=[],timerefcz=[],timercz=[],
xttime="undefined"!=typeof window.xttimez?window.xttimez:10,xtczdom;function xtIdxOf(a,b,d){var c=a.length;for(d=null==d?0:d;d<c;d++)if(a[d]==b)return d;return-1}
function xtT(a){if(a.innerHTML){a=a.innerHTML;if(RegExp("\x3cscript[^\x3e]*\x3e","gi").test(a.toString()))return fA;a=a.toString().replace(/<\/?[^>]+>/gi,"");a=a.toString().replace(RegExp("(\x26nbsp;)","g"),"");a=xtEn(a);a=a.toString().replace(RegExp("(%C2%A0)","g"),"");try{a=xtDe(a)}catch(b){}a=a.toString().replace(/[\s]/gm,"");return 0==a.length||a==un||a==nu?fA:a}return fA}
function xtE(a){this.xttab=[];this.xst=a;this.yr=this.xr=this.py=this.px=this.sy=this.sx=this.yc=this.xc=0;this.dest=this.cliccz=this.curr=this.af=this.bf="";this.s=0;this.s2cz=this.pcz="";this.idmod=this.t=0;this.s2=this.p="";this.idpage=-1}function xtH(){return(new Date).getTime()-xtel.xst}
function xtC(a){if(!a)if(xw.event)a=xw.event;else return{x:-1,y:-1};var b=-1,d=-1;if("number"==typeof a.pageX)b=a.pageX,d=a.pageY;else if("number"==typeof a.clientX)b=a.clientX,d=a.clientY,xw.xtn.userAgent.indexOf("Opera")+1||xw.ScriptEngine&&ScriptEngine().indexOf("InScript")+1||"KDE"==xtn.vendor||(xd.body&&(xd.body.scrollLeft||xd.body.scrollTop)?(b+=xd.body.scrollLeft,d+=xd.body.scrollTop):xd.documentElement&&(xd.documentElement.scrollLeft||xd.documentElement.scrollTop)&&(b+=xd.documentElement.scrollLeft,
d+=xd.documentElement.scrollTop));else return{x:-1,y:-1};return{x:b,y:d}}function xtAs(a){a=xtAb(a);return{w:a.right-a.left,h:a.bottom-a.top}}
function xtAb(a){if(a.rectDefined)return{left:a.rLeft,top:a.rTop,right:a.rRight,bottom:a.rBottom};a.shape||(a.shape="rect");var b=a.coords.split(","),d;if("rectangle"==a.shape.toLowerCase()||"rect"==a.shape.toLowerCase())d={left:parseInt(b[0]),top:parseInt(b[1]),right:parseInt(b[2]),bottom:parseInt(b[3])};if("circle"==a.shape.toLowerCase()||"circ"==a.shape.toLowerCase())d={left:parseInt(b[0])-parseInt(b[2]),top:parseInt(b[1])-parseInt(b[2]),right:parseInt(b[0])+parseInt(b[2]),bottom:parseInt(b[1])+
parseInt(b[2])};if("polygon"==a.shape.toLowerCase()||"poly"==a.shape.toLowerCase()){var c,f,g,k;for(d=0;d<b.length;d+=2){var h=parseInt(b[d]);if(c==un||h<c)c=h;if(g==un||h>g)g=h}for(d=1;d<b.length;d+=2){h=parseInt(b[d]);if(f==un||h<f)f=h;if(k==un||h>k)k=h}d={left:c,top:f,right:g,bottom:k}}a.rectDefined=tR;a.rLeft=d.left;a.rRight=d.right;a.rTop=d.top;a.rBottom=d.bottom;return d}
function xtAp(a,b){var d=xtpN(a);if(!d.dstElement){b||(b=xd);var c=b.getElementsByTagName("*");c.toArray&&(c=c.toArray());for(var f=0;f<c.length;f++){var g=c[f];if(g.useMap&&g.useMap.replace("#","")==d.name)break;g=nu}d.dstElement=g}return d.dstElement?(c=xtP(d.dstElement,"Left"),d=xtP(d.dstElement,"Top"),f=xtAb(a),{x:c+f.left,y:d+f.top}):{x:-1,y:-1}}
function xtP(a,b){if(typeof a.offsetParent!=un){for(var d="oEl.offset"+b,c=0;a;a=a.offsetParent)c+=eval(d);return c}return"Left"==b?a.x:"Top"==b?a.y:-1}function xtSx(a){var b="AREA"==xtnN(a)?xtAs(a).w:a.offsetWidth;if(b==nu||b==un||""==b)b=a.style.width!=nu?a.style.width:0;isS&&isM&&"TR"==xtnN(a)&&a.firstChild!=nu&&a.lastChild!=nu&&(b=a.lastChild.offsetLeft+a.lastChild.offsetWidth-a.firstChild.offsetLeft);if(b==nu||b==un||""==b)b=0;return parseInt(b,10)}
function xtSy(a){var b="AREA"==xtnN(a)?xtAs(a).h:a.offsetHeight;if(b==nu||b==un||""==b)b=a.style.height!=nu?a.style.height:0;isS&&isM&&"TR"==xtnN(a)&&a.firstChild!=nu&&a.lastChild!=nu&&(b=a.lastChild.offsetTop+a.lastChild.offsetHeight-a.firstChild.offsetTop);if(b==nu||b==un||""==b)b=0;return parseInt(b,10)}function xtPx(a){a="AREA"==xtnN(a)?xtAp(a).x:xtP(a,"Left");return parseInt(a,10)}
function xtPy(a){var b="AREA"==xtnN(a)?xtAp(a).y:xtP(a,"Top");isS&&isM&&"TR"==xtnN(a)&&a.firstChild!=nu&&(b+=a.firstChild.offsetTop);return parseInt(b,10)}function xtExD(a){a=a.replace(/((http)|(https)):\/\//g,"");var b=a.indexOf("/"),b=-1!=b?b:a.length;return a=xtSub(a,0,b)}
function xtCt(a,b){var d="",c=d="",f="",g="",k=xw.xt1!=nu&&""!=xw.xt1?xtSub(xw.xt1,8,xw.xt1.length):xd.domain,h="",l=!1,m=window.location.href,m=m.substring(0,0<m.indexOf("#")?m.indexOf("#"):m.length);if(a){if("INPUT"==xtnN(a)&&"submit"==a.type){try{c=xtG(a.form,"action").toString()}catch(p){}d=xtSub(c,c.lastIndexOf("."),c.length);h=xtExD(c)}if("IMG"!=xtnN(a)&&a.href)c=a.href.toString(),0<c.indexOf("#")&&c.substring(0,c.indexOf("#"))==m&&(l=!0),a.getAttribute("target")&&(f=a.getAttribute("target").toString()),
a.getAttribute("data-xtredir")&&(g=a.getAttribute("data-xtredir")),d=xtSub(c,c.lastIndexOf("."),c.length),h=xtExD(c);else for(var n=xtpN(a);n&&"BODY"!=xtnN(n);){if(n.href){c=n.href.toString();0<c.indexOf("#")&&c.substring(0,c.indexOf("#"))==m&&(l=!0);d=xtSub(c,c.lastIndexOf("."),c.length);h=xtExD(c);n.getAttribute("target")&&(f=n.getAttribute("target").toString());n.getAttribute("data-xtredir")&&(g=n.getAttribute("data-xtredir"));break}n=xtpN(n)}}d=xtEx(d)?"T":""!=h&&0>h.indexOf(k,0)&&h!=xtSub(k,
1,k.length)?"S":l?"A":"N";if(!b){255<c.length&&(c=xtSub(c,0,255));"/"==c.charAt(c.length-1)&&(c=xtSub(c,0,c.length-1));0<=c.lastIndexOf("/?",c.length)&&(c=c.replace("/?","?"));try{xtDe(c)!=nu&&xtDe(c)!=un&&(c=xtDe(c))}catch(q){}}return{typ:d,url:c,tgt:f,ck:g}}
function xtEx(a){for(var b=".aac .ace .ape .art .avi .bak .bat .bin .bmp .bsp .cab .ccd .cda .chm .clp .css .csv .cue dic dll .doc .dot .exe .fla .flac .gif .gz .hlp .ico .img .iso .jpeg .jpg .js .lnk .m2a .m2v .m3u .mdb .mdf .mds .mid .midi .mkv .mod .mov .mp2 .mp3 .mp4 .mpc .mpg .mpeg .msi .nfo .nrg .obd .ocx .ogg .old .ogm .pdf .png .pps .ppt .psd .psp .rar .raw .reg .rm .ram .rtf .swf .tar .tga .tgz .theme .tif .tiff .tmp .torrent .ttf .txt .url .vbs .vob .wab .wav .wdb .wks .wml .wma .wmv .wpf .xls .xml .zip .7z".split(" "),d=
0;d<b.length;d++)if(a==b[d])return tR;return fA}
function xtL(a){var b="INPUT SELECT IFRAME OBJECT AREA BUTTON".split(" "),d=xtnN(a);if("EMBED"==d&&"OBJECT"!=xtnN(xtpN(a))||"DIV"==d&&xtG(a,cL)||"SPAN"==d&&xtG(a,oC))return tR;if("SELECT"==d&&(xtG(a,"onchange")==nu||xtG(a,"onchange")==un||""==xtG(a,"onchange"))||"INPUT"==d&&"submit"!=a.type&&"image"!=a.type&&"button"!=a.type||"BUTTON"==d&&"submit"!=a.type)return fA;if("IMG"==d){for(var c=xtpN(a),f=fA;c;){if("A"==xtnN(c)&&(f=tR,xtG(c,oC)!=nu&&xtG(c,oC)!=un&&""!=xtG(c,oC)||xtG(c,"href")!=nu&&xtG(c,
"href")!=un&&""!=xtG(c,"href")))return tR;c=xtpN(c)}if(xtG(a,oC)!=nu&&xtG(a,oC)!=un&&""!=xtG(a,oC)&&!f)return tR}if("A"==d&&(xtG(a,oC)!=nu&&xtG(a,oC)!=un&&""!=xtG(a,oC)||xtG(a,"href")!=nu&&xtG(a,"href")!=un&&""!=xtG(a,"href"))){for(c=xtpN(a);c;){if("DIV"==xtnN(c)&&xtG(c,cL)||"SPAN"==xtnN(c)&&xtG(c,oC))return fA;c=xtpN(c)}d=b=fA;if(a.childNodes)for(a=a.childNodes,c=0;c<a.length&&(!b||!d);)"IMG"==xtnN(a[c])?b=tR:d=tR,c++;return b&&d?tR:b?fA:tR}for(a=0;a<b.length;a++)if(d==b[a])return tR;return fA}
function xtLCz(a){for(var b="DIV TABLE TR TD UL LI ARTICLE FOOTER ASIDE HEADER NAV SECTION".split(" "),d=xtnN(a),c=0;c<b.length;c++)if(d==b[c]&&1==a.nodeType&&xtG(a,cZ)!=nu&&xtG(a,cZ)!=un)return tR;return fA}
function xtNa(a){if(a&&!xtL(a))for(var b=xtpN(a);b;){if(xtL(b)){a=b;break}b=xtpN(b)}var d=null,c="",f="",g=f="",k="",d="",b=fA;if(a){if("A"==xtnN(a)&&a.childNodes)for(var d=a.childNodes,h=0;h<d.length&&!b;)1==d[h].nodeType&&!xtL(d[h])&&xtG(d[h],cL)&&(c=cL+xtG(d[h],cL),b=tR),h++;if(!b)if(xtG(a,oC)&&xtV(xtG(a,oC)))c=xtG(a,oC);else if(a.href&&xtV(a.href)){c=a.href;try{xtDe(c)!=nu&&xtDe(c)!=un&&(c=xtDe(c))}catch(l){}}else if(xtG(a,cL))c=cL+xtG(a,cL);else if(xtT(a))c=xtT(a);else if(a.id)c=a.id;else if(a.name)c=
a.name;else if(a.title)c=a.title;else if(a.value)c=a.value;else if(a.href){c=a.href.toString();"/"==c.charAt(c.length-1)&&(c=xtSub(c,0,c.length-1));d=c.lastIndexOf("/?",c.length);0<=d&&(c=c.replace("/?","?"));try{xtDe(c)!=nu&&xtDe(c)!=un&&(c=xtDe(c))}catch(m){}}else if(a.src){c=a.src.toString();"/"==c.charAt(c.length-1)&&(c=xtSub(c,0,c.length-1));d=c.lastIndexOf("/?",c.length);0<=d&&(c=c.replace("/?","?"));try{xtDe(c)!=nu&&xtDe(c)!=un&&(c=xtDe(c))}catch(p){}}else for(b=xtpN(a);b&&"BODY"!=xtnN(b);){if(xtG(b,
oC)&&xtV(xtG(b,oC))){c=xtG(b,oC);break}else if(b.href&&xtV(b.href)){c=b.href;try{xtDe(c)!=nu&&xtDe(c)!=un&&(c=xtDe(c))}catch(n){}break}else if(xtG(a,cL)){c=cL+xtG(a,cL);break}else if(xtT(b)){c=xtT(b);break}else if(b.id){c=b.id;break}else if(b.name){c=b.name;break}else if(b.title){c=b.title;break}else if(b.value){c=b.value;break}else if(b.href){c=b.href.toString();"/"==c.charAt(c.length-1)&&(c=xtSub(c,0,c.length-1));d=c.lastIndexOf("/?",c.length);0<=d&&(c=c.replace("/?","?"));try{xtDe(c)!=nu&&xtDe(c)!=
un&&(c=xtDe(c))}catch(q){}break}else if(b.src){c=b.src.toString();"/"==c.charAt(c.length-1)&&(c=xtSub(c,0,c.length-1));d=c.lastIndexOf("/?",c.length);0<=d&&(c=c.replace("/?","?"));try{xtDe(c)!=nu&&xtDe(c)!=un&&(c=xtDe(c))}catch(r){}break}b=xtpN(b)}c=c.toString().replace(/[\s]/gm,"");if(xtV(c))d=xtExT(c),k=d.typ,f=d.pag,g=d.sec,c=xtG(a,cL)?cL+xtG(a,cL):d.pagcl;else for(b=xtpN(a);b&&"BODY"!=xtnN(b);){if(xtG(b,oC)&&xtV(xtG(b,oC))){f=xtG(b,oC);f=f.toString().replace(/[\s]/gm,"");d=xtExT(f);k=d.typ;f=
d.pag;g=d.sec;break}else if(b.href&&xtV(b.href)){f=b.href;try{xtDe(f)!=nu&&xtDe(f)!=un&&(f=xtDe(f))}catch(s){}f=f.toString().replace(/[\s]/gm,"");d=xtExT(f);k=d.typ;f=d.pag;g=d.sec;break}b=xtpN(b)}if(""==k)if(xtG(a,cT)!=nu)k=xtG(a,cT);else for(b=xtpN(a);b&&"BODY"!=xtnN(b);){if(xtG(b,cT)!=nu){k=xtG(b,cT);break}b=xtpN(b)}""==k&&(k=xtCt(a).typ);d=xtCt(a).url;""==f&&(f=0<=c.indexOf(cL,0)?xtExTc(c):c,""==g&&(g=xtEx2(xw.xt9)));f=f.toString().replace(RegExp("(\x26)|[?]","g"),"_");""==g&&(g="0");c=c.toString().replace(RegExp("(::)",
"g"),"/");h=0;for(b=xtpN(a);b&&"BODY"!=xtnN(b);)xtLCz(b)&&2>h&&(c=xtG(b,cZ)+"::"+c,h+=1),b=xtpN(b)}c=xtSub(c,0,255);f=xtSub(f,0,255);return{id:c,pag:f,sec:g,typ:k,url:d}}function xtLDz(a){for(var b="DIV TABLE TR TD UL LI ARTICLE FOOTER ASIDE HEADER NAV SECTION".split(" "),d=xtnN(a),c=0;c<b.length;c++)if(d==b[c]&&1==a.nodeType&&xtG(a,cZ)!=nu&&xtG(a,cZ)!=un){for(a=xtpN(a);a;){if(1==a.nodeType&&xtG(a,cZ)!=nu&&xtG(a,cZ)!=un)return fA;a=xtpN(a)}return tR}return fA}
function xtTr(a){for(var b=["BODY","HTML"],d=0;d<b.length;d++)if(a.tagName==b[d]||"#document"===xtnN(a))return fA;return tR}function xtV(a){var b=/xt_click\(\s*this\s*\,\s*.?C/i;return/xt_med\(\s*.?C/i.test(a.toString())||b.test(a.toString())||(xw.xtczcustomtag?xw.xtczcustomtag.isPresent(a):!1)}
function xtExT(a){var b="",d="",c="",f=-1;if(d="undefined"!=typeof xw.xtczcustomtag?xw.xtczcustomtag.getCustomTag(a):null)c=d.typ||"",b=d.lab||"",f=d.sec||"";else{for(var d=0<=a.indexOf("xt_med")?0:1,g=0==d?a.indexOf("xt_med"):a.indexOf("xt_click"),k=a.indexOf("(",g),g=a.indexOf(")",g),h=xtSub(a,k+1,g),l=k;0<h.indexOf("(");)l=g+1,g=a.indexOf(")",g+1),h=xtSub(a,l+1,g);h=xtSub(a,k+1,g);xatab=h.split(/\,/);try{f=xatab[d+1]?String(eval(xatab[d+1])):""}catch(m){f=xatab[d+1]||""}try{b=xatab[d+2]?String(eval(xatab[d+
2])):""}catch(p){b=xatab[d+2]||""}try{c=xatab[d+3]?String(eval(xatab[d+3])):""}catch(n){c=xatab[d+3]||""}}d=b.replace(/(::)/g,"/");return{typ:c,pag:b,pagcl:d,sec:f}}function xtExTc(a){return a=a.replace(RegExp(cL,"gi"),"")}function xtEx2(a){var b=RegExp("\x26s2\x3d","gi");b.test(a.toString())&&(a=a.replace(b,""));return a}
function xtNodesload(){if(0!=xw.xt8){xw.xtczdom=xw.xtLogDom?xw.xtLogDom:".xiti.com/hit.xiti";for(var a=xd.getElementsByTagName("*"),b=0;b<a.length;b++)xtL(a[b])&&xtel.xttab.push(a[b]),xtLDz(a[b])&&20>xtobj.length&&xtobj.push(a[b]);for(a=0;a<xtel.xttab.length;a++)"OBJECT"==xtel.xttab[a].nodeName||"EMBED"==xtel.xttab[a].nodeName?xd.addEventListener?xtel.xttab[a].addEventListener("mousedown",xtR,fA):xd.attachEvent&&xtel.xttab[a].attachEvent("onmousedown",xtR):xd.addEventListener?xtel.xttab[a].addEventListener("click",
xtR,fA):xd.attachEvent&&xtel.xttab[a].attachEvent("onclick",xtR);for(a=0;a<xtobj.length;a++)xtcz[a]=xtG(xtobj[a],cZ),xtG(xtobj[a],dT)!=nu&&xtG(xtobj[a],dT)!=un?typcz[a]=xtG(xtobj[a],dT):typcz[a]="0",sizex[a]=xtSx(xtobj[a]),sizey[a]=xtSy(xtobj[a]),posx[a]=xtPx(xtobj[a]),posy[a]=xtPy(xtobj[a]),timecz[xtcz[a]]=0,timerefcz[xtcz[a]]=0,timercz[xtcz[a]]=nu;xtReload();xw.addEventListener?(xw.addEventListener("scroll",xtReload,fA),xw.addEventListener("resize",xtReload,fA),xw.addEventListener("focus",xtReload,
fA),xw.addEventListener("blur",xtCTimer,fA)):xw.attachEvent&&(xw.attachEvent("onscroll",xtReload),xw.attachEvent("onresize",xtReload));xd.addEventListener?(xd.addEventListener("mousemove",xtRefresh,fA),xd.addEventListener("keydown",xtRefresh,fA)):xd.attachEvent&&(xd.attachEvent("onfocusin",xtReload),xd.attachEvent("onfocusout",xtCTimer),xd.attachEvent("onmousemove",xtRefresh),xd.attachEvent("onkeydown",xtRefresh))}}function xtRefresh(){for(var a=0;a<xtobj.length;a++)timerefcz[xtcz[a]]=0}
function xtReload(){larg=xtcW();haut=xtcH();xtAffDz()}function xtCTimer(){for(var a=0;a<xtobj.length;a++)timercz[xtcz[a]]!=nu&&(xw.clearInterval(timercz[xtcz[a]]),timercz[xtcz[a]]=nu,timerefcz[xtcz[a]]=0)}
function xtTime(a){timercz[xtcz[a]]!=nu&&(timecz[xtcz[a]]+=1,timerefcz[xtcz[a]]+=1,0==timerefcz[xtcz[a]]%xttime&&(xw.clearInterval(timercz[xtcz[a]]),timercz[xtcz[a]]=nu,timerefcz[xtcz[a]]=0,xd.addEventListener?(xd.addEventListener("mousemove",xtAffDz,fA),xd.addEventListener("keydown",xtAffDz,fA)):xd.attachEvent&&(xd.attachEvent("onmousemove",xtAffDz),xd.attachEvent("onkeydown",xtAffDz))))}
function xtAffDz(){xd.removeEventListener?(xd.removeEventListener("mousemove",xtAffDz,fA),xd.removeEventListener("keydown",xtAffDz,fA)):xd.detachEvent&&(xd.detachEvent("onmousemove",xtAffDz),xd.detachEvent("onkeydown",xtAffDz));for(var a=0;a<xtobj.length;a++){var b=xtsT(),d=xtsL(),c=0,f=c=0;posy[a]>=b&&posy[a]+sizey[a]<=b+haut?f=100:posy[a]<b&&posy[a]+sizey[a]<=b||posy[a]>=b+haut?f=0:posy[a]<=b&&posy[a]+sizey[a]>=b+haut?f=100*(haut/sizey[a]):posy[a]<b?f=100*((posy[a]+sizey[a]-b)/sizey[a]):posy[a]+
sizey[a]>b+haut&&(f=100*((b+haut-posy[a])/sizey[a]));posx[a]>=d&&posx[a]+sizex[a]<=d+larg?c=100:posx[a]<d&&posx[a]+sizey[a]<=d||posx[a]>=d+larg?c=0:posx[a]<=d&&posx[a]+sizex[a]>=d+larg?c=100*(larg/sizex[a]):posx[a]<d?c=100*((posx[a]+sizex[a]-d)/sizex[a]):posx[a]+sizex[a]>d+larg&&(c=100*((d+larg-posx[a])/sizex[a]));c=Math.round(100*(c*sizex[a]/100*(f*sizey[a]/100)/(sizex[a]*sizey[a])));timercz[xtcz[a]]!=nu&&(xw.clearInterval(timercz[xtcz[a]]),timercz[xtcz[a]]=nu,timerefcz[xtcz[a]]=0);0<c&&(timercz[xtcz[a]]=
xw.setInterval("xtTime("+a+");",1E3));xtCDz(xtcz[a],c,0==c?0:1,typcz[a])}}
function xtR(a){xtel.t=Math.round(xtH()/1E3);if(!(0!=xtdtmp&&1>xtel.t-xtdtmp||(xtdtmp=xtel.t,a||(a=xw.event),xtBdEv(a)))){var b=null,d=xtEv(a);if(xtTr(d)){if("OPTION"==xtnN(d))for(b=xtpN(d);b;){d=b;if("SELECT"==xtnN(d))break;b=xtpN(b)}xtel.s=xw.xt8;xtel.pcz=xw.xtp;xtel.s2cz=xtEx2(xw.xt9);xtel.idmod="undefined"!=typeof xw.xtidmod?xw.xtidmod:0;b=xtNa(d);xtel.curr=b.id;xtel.cliccz=b.typ;xtel.dest=b.url;xtel.p=b.pag;xtel.s2=b.sec;xtel.p=""!=xtel.p&&"F"!=xtel.cliccz?"\x26pmed\x3d"+xtEn(xtel.p):"";xtel.s2=
""!=xtel.s2&&"F"!=xtel.cliccz?"\x26s2med\x3d"+xtEn(xtel.s2):"";"F"==xtel.cliccz&&(xtel.cliccz=xtCt(xl).typ);xtel.sx=xtSx(d);xtel.sy=xtSy(d);xtel.px=xtPx(d);xtel.py=xtPy(d);xtel.idpage=xw.xtidpg!=nu?xw.xtidpg:-1;if(-1!=xtel.px||-1!=xtel.py)if(b=xtEv(a),xtel.xc="OPTION"!=xtnN(b)||isOP?xtC(a).x:xtC(a).x+xtel.px,xtel.yc=xtC(a).y,-1!=xtel.xc||-1!=xtel.yc){"BackCompat"==xd.compatMode&&isI&&(xtel.xc-=2,xtel.yc-=2);xtel.xr=(xtel.xc-xtel.px)/xtel.sx;xtel.yr=(xtel.yc-xtel.py)/xtel.sy;0<xtel.sx&&40>=xtel.sx&&
(xtel.xr=0.5);40<xtel.sx&&250>=xtel.sx&&(xtel.xr=Math.round(10*xtel.xr)/10);250<xtel.sx&&(xtel.xr=Math.round(100*xtel.xr)/100);0<xtel.sy&&40>=xtel.sy&&(xtel.yr=0.5);40<xtel.sy&&250>=xtel.sy&&(xtel.yr=Math.round(10*xtel.yr)/10);250<xtel.sy&&(xtel.yr=Math.round(100*xtel.yr)/100);0>xtel.xr&&(xtel.xr=0);0>xtel.yr&&(xtel.yr=0);1<xtel.xr&&(xtel.xr=1);1<xtel.yr&&(xtel.yr=1);if(0>xtel.curr.indexOf("xtclib",0)){for(var c=xtIdxOf(xtel.xttab,d),b=xtpN(d);-1==c&&b;)c=xtIdxOf(xtel.xttab,b),b=xtpN(b);xtel.bf=xtNa(xtel.xttab[c-
1]).id;xtel.af=xtNa(xtel.xttab[c+1]).id;xtel.bf=0<=xtel.bf.indexOf("xtclib",0)?xtExTc(xtel.bf):xtel.bf;xtel.af=0<=xtel.af.indexOf("xtclib",0)?xtExTc(xtel.af):xtel.af}else xtel.curr=xtExTc(xtel.curr),xtel.bf="",xtel.af="",xtel.dest="";b="";b="EMBED"==xtnN(d)&&isOP&&xtpN(d)!=nu&&xtpN(d)!=un?xtpN(d).name:d.name;b!=nu&&b!=un&&0<=b.indexOf(cT)&&(xtel.cliccz=b.replace(cT,""));c=xtCt(d).typ;b=fA;"N"==xtel.cliccz&&"N"!=c&&(b=tR);c=RegExp("(\x26)|[?]","g");xtel.curr=xtel.curr.toString().replace(c,"_");xtel.bf=
xtel.bf.toString().replace(c,"_");xtel.af=xtel.af.toString().replace(c,"_");xtel.dest=xtel.dest.toString().replace(c,"_");var c="\x26xtczv\x3d"+xtczv+"\x26idmod\x3d"+xtel.idmod+"\x26current\x3d"+xtEn(xtel.curr)+"\x26before\x3d"+xtEn(xtel.bf)+"\x26after\x3d"+xtEn(xtel.af)+"\x26cliccz\x3d"+xtel.cliccz+"\x26dest\x3d"+xtEn(xtel.dest)+"\x26posx\x3d"+xtel.xr+"\x26posy\x3d"+xtel.yr+"\x26time\x3d"+xtel.t+xtel.p+xtel.s2,f="\x26dz\x3d";if(xt_valdz!=nu)for(var g=RegExp("[|]{2}","gi"),k=[],k=xt_valdz.split(RegExp("XTL",
"gi")),h=0;h<k.length;h++)0<k[h].length&&0<parseInt(k[h].split(g)[1],10)&&(f+=k[h].split(g)[0]+",",f+=k[h].split(g)[1]+",",f+=k[h].split(g)[2]+",",f+=k[h].split(g)[4]+",",f+=timecz[k[h].split(g)[0]]+"|");h=xtCt(d,1);d=h.url;g=h.tgt;k=!1;h=h.ck;xtautoredir&&"click"==a.type&&"no"!=h&&0==d.indexOf("http")&&"_blank"!=g&&!a.defaultPrevented&&"S"==xtel.cliccz&&(a.preventDefault(),k=1);2==scriptOnClickZone&&"N"!=xtel.cliccz||b==tR?(a="","S"==xtel.cliccz&&(hit=tR,a=f),xtHit(xtsd+xw.xtczdom+"?s\x3d"+xtel.s+
"\x26pcz\x3d"+xtEn(xtel.pcz)+"\x26s2cz\x3d"+xtEn(xtel.s2cz)+("undefined"!=typeof xt40?"\x26idclient\x3d"+xt40:""),c+a,1,1,xtel.idpage),k&&xtRedir(d,g)):2!=scriptOnClickZone&&"S"==xtel.cliccz?(hit=tR,xtHit(xtsd+xw.xtczdom+"?s\x3d"+xtel.s+"\x26pcz\x3d"+xtEn(xtel.pcz)+"\x26s2cz\x3d"+xtEn(xtel.s2cz)+"\x26idmod\x3d"+xtel.idmod+"\x26xtczv\x3d"+xtczv+("undefined"!=typeof xt40?"\x26idclient\x3d"+xt40:""),f,1,1,xtel.idpage),k&&xtRedir(d,g)):"N"==xtel.cliccz&&(hit=tR,xtCzWc("\x26idpcz\x3d"+xtel.idpage+(43005<
parseInt(xw.xtv.substring(0,xw.xtv.indexOf("-")),10)?c.replace("\x26current\x3d","\x26c\x3d").replace("\x26before\x3d","\x26b\x3d").replace("\x26after\x3d","\x26a\x3d"):c)+f))}}}}
function xtRedir(a,b){var d="undefined"!=typeof xw.xttredir?xw.xttredir:500;switch(b){case "_self":setTimeout('self.location.href\x3d"'+a+'"',d);break;case "_top":setTimeout('top.location.href\x3d"'+a+'"',d);break;case "_parent":setTimeout('parent.location.href\x3d"'+a+'"',d);break;case "":setTimeout('self.location.href\x3d"'+a+'"',d);break;default:setTimeout('self.location.href\x3d"'+a+'"',d)}}
function xtCDz(a,b,d,c){var f=d,g=0,k=0,h=fA,f=RegExp("XTL","gi"),l=RegExp("[|]{2}","gi"),m="";if(xt_valdz!=nu){for(var p=[],p=xt_valdz.split(f),n=0;n<p.length;n++)if(0<p[n].length){g=parseInt(p[n].split(l)[1],10);f=parseInt(p[n].split(l)[2],10);k=parseInt(p[n].split(l)[3],10);if(0==k&&0<parseInt(b,10)&&g!=parseInt(b,10))try{xt_areaDisplayed(p[n].split(l)[0])}catch(q){}a==p[n].split(l)[0]&&(h=tR,parseInt(b,10)>parseInt(p[n].split(l)[1],10)?(g=parseInt(b,10),f=1,k=parseInt(b,10)):parseInt(b,10)==parseInt(p[n].split(l)[1],
10)&&parseInt(p[n].split(l)[3],10)<parseInt(b,10)?(f=parseInt(p[n].split(l)[2],10)+1,k=parseInt(b,10)):parseInt(b,10)<parseInt(p[n].split(l)[1],10)&&(k=parseInt(b,10)));m+=p[n].split(l)[0]+"||"+g+"||"+f+"||"+k+"||"+p[n].split(l)[4]+"XTL"}h||(m+=a+"||"+b+"||"+d+"||"+b+"||"+c+"XTL")}else m=a+"||"+b+"||"+d+"||"+b+"||"+c+"XTL";xt_valdz=m}function xtEv(a){var b;a.target?b=a.target:b=a.srcElement;return b}function xtBdEv(a){return xw.event?2==xw.event.button:3==a.which}
function xtCzWc(a){var b=new Date;b.setTime(b.getTime()+45E3);xd.cookie="xtvalCZ\x3d"+a+";expires\x3d"+b.toGMTString()+" ;path\x3d/"+xw.xt1}function xtcW(){var a=xtfR(xw.innerWidth?parseInt(xw.innerWidth,10):0,xd.documentElement?parseInt(xd.documentElement.clientWidth,10):0),b=xd.body?parseInt(xd.body.clientWidth,10):0;return 0==a?b:a}
function xtcH(){var a=xtfR(xw.innerHeight?parseInt(xw.innerHeight,10):0,xd.documentElement?parseInt(xd.documentElement.clientHeight,10):0),b=xd.body?parseInt(xd.body.clientHeight,10):0;return 0==a?b:a}function xtsT(){var a=xw.pageYOffset?parseInt(xw.pageYOffset,10):0,b=xd.documentElement?parseInt(xd.documentElement.scrollTop,10):0,d=xd.body?parseInt(xd.body.scrollTop,10):0;return xtMax(xtMax(a,b),d)}
function xtsL(){var a=xw.pageXOffset?parseInt(xw.pageXOffset,10):0,b=xd.documentElement?parseInt(xd.documentElement.scrollLeft,10):0,d=xd.body?parseInt(xd.body.scrollLeft,10):0;return xtMax(xtMax(a,b),d)}
function xtHit(a,b,d,c,f){var g=new Image,k="\x26mh\x3d"+d+"-"+c+"-"+f;if(1500<b.length){for(var h=b.split(RegExp("[|]","gi")),l="",k=h[0].length,m=0;1500>k&&m<h.length;)l+=h[m]+"|",m<h.length-1&&(k+=h[m+1].length+1),m+=1;c=1==c?Math.ceil(b.length/1500):c;k="\x26mh\x3d"+d+"-"+c+"-"+f;if(""!=l){g.src=a+"\x26idpcz\x3d"+f+k+l;g.onload=function(){g.onload=null};b="\x26dz\x3d";for(l=m;l<h.length;l++)b+=h[l]+(l==h.length-1?"":"|");xtHit(a,b,d+1,c,f)}else g.src=a+"\x26idpcz\x3d"+f+k+b.substring(0,1500)+
"\x26mherr\x3d1",g.onload=function(){g.onload=null}}else 4<b.length&&(g.src=1==d?a+"\x26idpcz\x3d"+f+b:a+"\x26idpcz\x3d"+f+k+b,g.onload=function(){g.onload=null})}function xtG(a,b){var d=null;try{d=a.getAttribute(b)}catch(c){}return null==d?null:b==cZ&&255<d.length?xtSub(d,0,255):d}function xtfR(a,b){var d=a?a:0;b&&(!d||d>b)&&(d=b);return d}function xtMax(a,b){return a>b?a:b}function xtEn(a){return encodeURIComponent(a)}function xtDe(a){return decodeURIComponent(a)}
function xtnN(a){return a.nodeName}function xtpN(a){return a.parentNode}function xtSub(a,b,d){return a.substring(b,d)};